### ISSUE TITLE
Move implementation of DaphneDistributableOpInterface to separate file

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#100]
In GitLab by @pdamme on Jul 30, 2021, 19:13

This custom MLIR interface plays an important role for our distributed operations. It needs to be implemented for each DaphneIR operation that shall support distribution. Currently, there is only an implementation for `EwAddOp`, which resides in `src/ir/daphneir/DaphneDialect.cpp`. To facilitate a clear separation in the code, we should move this to a separate file. This file could reside either in `src/ir/daphneir/` (where the interface resides), or in `src/compiler/lowering` (where the pass utilizing it resides). The latter would be the better choice to my mind.

**Comment by philipportner** [comment]
Closing this, has been done in c8006ee56471def83f23c044079e0ad14fcb0de6
