### ISSUE TITLE
Compiler support for update-in-place, especially in vectorized pipelines

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#112]
In GitLab by @pdamme on Aug 25, 2021, 22:32

Currently `MTWrapper` allocates a data object for the output of a vectorized pipeline, but since we still lack compiler support for update-in-place (kernel calls are always passed a null-pointer for their result parameter), we still need to copy a pipeline's output to the actual output object. This is an unnecessary step and we should avoid it.

**Comment by pdamme** [comment]
I'm closing this issue because it has just been replaced by a new one (#498) with a broader scope and a more detailed description.
