### ISSUE TITLE
Sorting rows in a frame

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#125]
In GitLab by @pdamme on Sep 14, 2021, 22:27

When testing kernels for relational DaphneIR operations, the comparison of the obtained and expected result should be insensitive to the row order. One way to achive this is to sort one (or both) of these frames before the comparison. We need to (a) finalize the DaphneIR operation for that (currently we have a WIP OrderOp), and (b) implement a kernel.

Besides for writing test cases, this feature would be useful to users as a built-in function in DaphneDSL as well.

**Comment by pdamme** [comment]
This issue was addressed a while ago by #327.
