### ISSUE TITLE
Harmonize include styles

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#16]
In GitLab by @pdamme on Mar 17, 2021, 19:41

Currently, header files are included in different style, e.g.

- `#include "somefile.h"`
- `#include "path/to/somefile.h"`
- `#include <path/to/somefile.h>`

We should harmonize this.

**Comment by philipportner** [comment]
This is talked about in both, the ISO C++ specification and the C++ core guidelines.

From the core guidelines: [link](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rs-incform)
```
.. the guidance is to use the quoted form for including files that exist at a
relative path to the file containing the #include statement (from within 
the same component or project) and to use the angle bracket form everywhere else ..
```
From the specification: [link](http://eel.is/c++draft/cpp.include)
