### ISSUE TITLE
consider switching to 'main' branch

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#184]
In GitLab by @auge on Feb 1, 2022, 11:18

the name 'master' for the main development branch is being replaced by more and more git hosting systems, we should also work towards a more inclusive name?

KR, Benjamin

- https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/
- ...

**Comment by corepointer** [comment]
Now that people need to change settings in their working copies anyway after the switch to github, we should get this change done soon.

**Comment by pdamme** [comment]
Fully agree! I'm looking into it now.

**Comment by pdamme** [comment]
It turned out to be quite simple on GitHub. See https://github.com/github/renaming and https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch.
