### ISSUE TITLE
Conversion tool DML to DaphneDSL

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#197]
In GitLab by @pdamme on Mar 1, 2022, 19:16

DaphneDSL, DAPHNE's domain specific language, offers all necessary means for writing complex linear/relational algebra programs. However, implementing typical ML algorithms in such a DSL is a complex and time-intensive task. At the same time, the usefulness of the DAPHNE system depends on a rich library of algorithms. Interestingly, Apache SystemDS already has such a library, written in DML. Thus, our goal is to translate these DML scripts to DaphneDSL automatically.

The task is to implement a stand-alone tool (in Python, C/C++, or Java) which converts a given DML script into an equivalent DaphneDSL script. A documentation of both languages as well as ANTLR grammar definitions are already given.

**Comment by pdamme** [comment]
I'm closing this issue, because it has just been replaced by a new issue (#497) with a more detailed description.
