### ISSUE TITLE
MCSR matrix representation

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#201]
In GitLab by @pdamme on Mar 1, 2022, 19:26

Currently, the DAPHNE system supports two physical matrix representations: dense and compressed sparse row (CSR). In CSR, a matrix is represented by three dense arrays: values, column indexes, and row-offsets. While this format is suitable for storing and reading sparse matrices, it suffers from inefficient (random) writes/updates. Modified compressed sparse row (MCSR) is a more update-friendly sparse matrix representation. Here, individual values and column index arrays are allocated for each row.

The task is to implement (C++) an MCSRMatrix class, whereby inspiration can be takes from the existing CSR implementation. To see this new data structure in action, a few simple kernels (e.g., elementwise addition) shall be implemented for MCSRMatrix as well. Larger teams may also tackle the integration of MCSRMatrix into DAPHNE's vectorized execution engine.

**Comment by pdamme** [comment]
I'm closing this issue because it has just been replaced by a new one (#501) with a broader scope and more detailed description.
