### ISSUE TITLE
Timing/monitoring infrastructure

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#206]
In GitLab by @pdamme on Mar 8, 2022, 17:14

While it's easy to measure the end-to-end runtime of a DaphneDSL script using command-line tools like `time`, fine-grained insights into where time is spent would be invaluable for understanding, profiling, and improving the system. For that purpose, we need some kind of timing (or more generally, monitoring) infrastructure. (Note that right now we have the `now()` built-in function in DaphneDSL, which can be used for very simple time measurements. However, this approach has downsides, e.g., in presence of reordering compiler passes.)

It may start very simple by just measuring the time for the high-level steps of *parsing*, *optimizing/compiling*, and *executing* a DaphneDSL script.

Building upon that, more fine-grained insights would be highly welcome:
- Optimizer/compiler: How much time is spent on which pass
- Runtime: How much time is spent on which (kind of) operation/kernel

Besides runtime, other measurables would be interesting as well, e.g., memory consumption, performance counters, ...

**Comment by philipportner** [comment]
All of the above (- memory) is already part of DAPHNE or MLIR, see #740. In case we want to add memory statistics, I suggest opening a new issue for that, or use [UMLAUT](https://github.com/daphne-eu/umlaut).
