### ISSUE TITLE
Ternary/conditional operator `?:` in DaphneDSL

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#215]
In GitLab by @pdamme on Mar 8, 2022, 18:39

Many script/programming languages offer a ternary/conditional operator, which evaluates a condition and, depending on the outcome, returns the value of one of the two given expressions. For instance, in `C`-like languages, this is done by
```
v = conditionExpr ? thenExpr : elseExpr;
```

Something similar (can be exactly the same syntax) would be very handy in DaphneDSL, too. Supporting this requires:
1. Adding a new kind of expression in the DaphneDSL ANTLR grammar in `src/parser/daphnedsl/DaphneDSLGrammar.g4`.
2. Adding a visitor function for this new kind of expression in `src/parser/daphnedsl/DaphneDSLVisitor.h/cpp`.
3. Adding a some script-level test cases in `test/api/cli/expressions` (to be created).

**Hints:**
- The ternary/conditional operator is essentially just syntactic sugar for an if-then-else statement. Therefore, instead of implementing a completely new visitor, the try to reuse the code in `DaphneDSLVisitor::visitIfStatement()`. This will also ensure that exactly the same restrictions hold for both constructs (e.g., regarding types of the then/else branches' outcomes).

**Comment by akroviakov** [comment]
Assigned to @akroviakov.
