### ISSUE TITLE
rowBind-kernel for CSRMatrix

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#217]
In GitLab by @pdamme on Mar 11, 2022, 12:48

The `rowBind`-operation concatenates two matrices or frames `lhs` and `rhs` vertically and returns the result as a new data object `res`. The two inputs must have the same number of columns.

**Example**

```
lhs: 1, 2, 3,
     4, 5, 6,

rhs: 0, 1, 0,
     1, 0, 1,
     0, 1, 0,

res: 1, 2, 3,
     4, 5, 6,
     0, 1, 0,
     1, 0, 1,
     0, 1, 0,
```

We already have specializations of the `rowBind`-kernel for `DenseMatrix` and `Frame`, but still lack one for `CSRMatrix`.

**This issue asks you to implement**

1. A partial specialization of the kernel struct for `CSRMatrix` as the data type implementation of all input and output matrices.
2. Ideally some test cases.

**Hints**
- Have a look at the [guidelines on implementing a built-in kernel](https://gitlab.know-center.tugraz.at/daphne/prototype/-/blob/master/doc/ImplementBuiltinKernel.md).

**Comment by akroviakov** [comment]
Assigned to @akroviakov.
