### ISSUE TITLE
Statistics component in Daphne

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#227]
In GitLab by @corepointer on Mar 18, 2022, 11:32

Similar to the stats output of SystemDS we would benefit of stats collection in Daphne as well.
The challenge would be an approach that has low impact on actual runtime.

**Comment by philipportner** [comment]
FYI: I'm working on this one, PR coming soon.
Is able to display the top K kernel functions by time spent, and even the top K source code lines from the DSL script. User will be able to choose with a flag. I think as a default setting, simply the source loc makes more sense, if someone wants to know which actual kernel spent how much time than we'll have the flag for that.

**Comment by pdamme** [comment]
@philipportner I think this issue has been addressed by d4cf91031dcebe2467ca9b07c9e651c77f3917ff. Can we close this issue? Additional improvements could be subject to more specific follow-up issues.

**Comment by philipportner** [comment]
Yes, thanks for catching that.
