### ISSUE TITLE
Build script fails when gcc is the default compiler

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#241]
In GitLab by @jonnygiger on Mar 28, 2022, 16:43

Currently, when running the build.sh script on a fresh install of Ubuntu it will fail due to googletest which is a dependency of utfcpp which is a dependency of antlr. 

<details><summary>Error output</summary>
FAILED: extern/gtest/googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o 
/usr/bin/c++  -I/home/jonny/prototype/thirdparty/antlr/antlr4-cpp-runtime-4.9.2-source/build/runtime/thirdparty/utfcpp/extern/gtest/googletest/include -I/home/jonny/prototype/thirdparty/antlr/antlr4-cpp-runtime-4.9.2-source/build/runtime/thirdparty/utfcpp/extern/gtest/googletest -Wall -Wshadow -Werror -Wno-error=dangling-else -DGTEST_HAS_PTHREAD=1 -fexceptions -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -MD -MT extern/gtest/googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o -MF extern/gtest/googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o.d -o extern/gtest/googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o -c /home/jonny/prototype/thirdparty/antlr/antlr4-cpp-runtime-4.9.2-source/build/runtime/thirdparty/utfcpp/extern/gtest/googletest/src/gtest-all.cc
In file included from /home/jonny/prototype/thirdparty/antlr/antlr4-cpp-runtime-4.9.2-source/build/runtime/thirdparty/utfcpp/extern/gtest/googletest/src/gtest-all.cc:42:
/home/jonny/prototype/thirdparty/antlr/antlr4-cpp-runtime-4.9.2-source/build/runtime/thirdparty/utfcpp/extern/gtest/googletest/src/gtest-death-test.cc: In function ‘bool testing::internal::StackGrowsDown()’:
/home/jonny/prototype/thirdparty/antlr/antlr4-cpp-runtime-4.9.2-source/build/runtime/thirdparty/utfcpp/extern/gtest/googletest/src/gtest-death-test.cc:1224:24: error: ‘dummy’ may be used uninitialized [-Werror=maybe-uninitialized]
 1224 |   StackLowerThanAddress(&dummy, &result);
      |   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/home/jonny/prototype/thirdparty/antlr/antlr4-cpp-runtime-4.9.2-source/build/runtime/thirdparty/utfcpp/extern/gtest/googletest/src/gtest-death-test.cc:1214:13: note: by argument 1 of type ‘const void*’ to ‘void testing::internal::StackLowerThanAddress(const void*, bool*)’ declared here
 1214 | static void StackLowerThanAddress(const void* ptr, bool* result) {
      |             ^~~~~~~~~~~~~~~~~~~~~
/home/jonny/prototype/thirdparty/antlr/antlr4-cpp-runtime-4.9.2-source/build/runtime/thirdparty/utfcpp/extern/gtest/googletest/src/gtest-death-test.cc:1222:7: note: ‘dummy’ declared here
 1222 |   int dummy;
      |       ^~~~~
cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.
ninja: build stopped: subcommand failed.
</details>

Setting clang as the default compiler fixes this. Since our documentation already lists clang as a requirement, should the build script specify clang as the compiler?

**Comment by corepointer** [comment]
This used to build just fine with the default gcc from Ubuntu 20 iirc. Maybe you have a more modern version of Ubuntu with a more recent gcc, which is more strict (I ran into that problem as well with Ubuntu 21.10 and Manjaro). Builds just fine with gcc when that dummy variable mentioned in the error message is initialized to zero. I have a patch for this in the pipeline. I'll add it after processing PR #328
