### ISSUE TITLE
Add selected algorithms

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#243]
In GitLab by @mboehm7 on Mar 30, 2022, 18:33

* lmDS (regression)
* lmCG (regression)
* MLogreg (classification)
* PCA (dim reduction)
* KMeans (clustering)
* Components (graph)
* PageRank (graph)

**Comment by philipportner** [comment]
All but `MLogreg` and `PCA` are already implemented.

**Comment by philipportner** [comment]
Closed as only `MLogreg` and `PCA` have not been implemented, in case someone wants those please reopen or ideally, create a new issue.
