### ISSUE TITLE
DaphneDSL: rbind checks number of rows instead the number of columns

### ISSUE THREAD

**Issue by RetoKrummenacher** [daphne-eu/daphne#350]
```rbind``` is checking the number of rows instead of columns.

```
r = rand(1,5,0,1,1,-1);
r2 = rand(1,5,1,2,1,-1);
r3 = rand(1,5,2,3,1,-1);
print(r);
print(r2);
print(r3);
r = rbind(r,r2);
print(r);
r = rbind(r,r3);
```
Ouput:
![grafik](https://user-images.githubusercontent.com/71382164/167208406-5b81b5c0-0f63-44e5-be0f-5fd467a94756.png)

**Comment by aristotelis96** [comment]
Thank you @RetoKrummenacher for openning this issue. I've pushed a PR that should fix this error.
