### ISSUE TITLE
DaphneDSL: Wrong printing of calculated variables

### ISSUE THREAD

**Issue by RetoKrummenacher** [daphne-eu/daphne#351]
Printing variables that have been assigned a value to is working fine. Printing variables that have been calculated, however, places the variable at the beginning of the concatenated string.

```
time_convert = 200;
print("Time spend: " + time_convert + " seconds");
time_convert = 200 - 20;
print("Time spend:" + time_convert + " seconds");
```

Output:
![grafik](https://user-images.githubusercontent.com/71382164/167212505-332b9f3d-3cde-47b9-b3af-8a16211d8392.png)

**Comment by pdamme** [comment]
Thanks for reporting this bug! We'll fix it soon.
