### ISSUE TITLE
DaphneDSL: Return from nrow() is not usable in arithmetic operations.

### ISSUE THREAD

**Issue by RetoKrummenacher** [daphne-eu/daphne#355]
The function ```nrow``` returns a type that is not usable in simple arithmetic operations:
```
m = rand(5,5,0.0,1.0,1,-1);
n = nrow(m);
print(n); # working
print(n+1); # not working
# Output: 
# error: 'daphne.ewAdd' op operand #0 must be matrix of numeric 
# or placeholder for an unknown type values or numeric, but got 'index'
```

It would be helpful if it was a scalar to do simple arithmetic, like to calculate the number of iterations needed.

**Comment by pdamme** [comment]
Thanks for identifying this bug! `nrow()` does return a scalar (of type `index`), but due to current limitations in type handling, this error occurs. We will definitely fix it. In the meantime you can use `as.si64(n)+1` as a workaround.
