### ISSUE TITLE
DaphneDSL: Type casting matrices

### ISSUE THREAD

**Issue by RetoKrummenacher** [daphne-eu/daphne#356]
The type conversion on matrices is not working. 

```
A = rand(5,5,0.0,1.0,1,-1);
print(A);
B = as.matrix.f32(A);
# Output:
# JIT session error: Symbols not found: 
#[ _cast__DenseMatrix_float__DenseMatrix_double ]
```

![grafik](https://user-images.githubusercontent.com/71382164/167217951-e299d017-8afe-40c2-8549-eef81135cc76.png)

**Comment by aristotelis96** [comment]
Thank you @RetoKrummenacher for this issue. PR #337 implemented the kernel for casts between different value types of a DenseMatrix, however `src/runtime/local/kernels/kernels.json` is missing the entries. I've created a PR that should fix this.
