### ISSUE TITLE
DaphneDSL: type/shape of a variable must not be changed in loops

### ISSUE THREAD

**Issue by RetoKrummenacher** [daphne-eu/daphne#371]
It is not possible to combine matrices with rbind() and cbind() in loops. It is unclear to me if this is a desired behavior. If it is, it should be mentioned in [DaphneDSL documentation](https://github.com/daphne-eu/daphne/blob/118-doc-daphnedsl/doc/DaphneDSL.md).

While-loop:
```
m = fill(0.0,1,1);
iter = 1;
while (iter < 11) {
	e = fill(0.0,1,1);
	m = rbind(m,e);	
	iter = iter + 1;
}
```
![grafik](https://user-images.githubusercontent.com/71382164/169326404-921ccc9f-b0c5-4aeb-93a6-db4712477838.png)

For-loop:
```
m = fill(0.0,1,1);
for (iter in 1:10) {
	e = fill(0.0,1,1);
	m = cbind(m,e);
}
```
![grafik](https://user-images.githubusercontent.com/71382164/169326959-0373d35f-6575-47b5-820c-5b4bb922eb3f.png)

**Comment by pdamme** [comment]
Thanks for identifying the issue, @RetoKrummenacher. We want both of these scripts to work, but currently there are still issues with shape inference that make them fail. It's on my list to fix them.
