### ISSUE TITLE
Connect JSON-based file meta data parser to file IO

### ISSUE THREAD

**Issue by pdamme** [daphne-eu/daphne#385]
Since recently (dcf90639baff66394fbfbc2267c7a1a965223796), we have a parser for a JSON-based file meta data file format. Currently, this is still disconnected from the rest of the code base. 

**What needs to be done**
1. `FileMetaData::ofFile()` should use the new `MetaDataParser` internally.
2. `FileMetaData::toFile()` should create a JSON file that can be read again by `MetaDataParser`.
3. Existing meta data files in the test cases (primarily in `test/runtime/local/io/`) need to be converted to the new JSON-based format.

**Hints**
- I recommend keeping the interface of `FileMetaData` (and not marking it deprecated). That way, we don't need to modify all places where it is used in the compiler and runtime.
- The old meta data file format does not need to be supported at all anymore and can be removed altogether.

**Comment by matejmoravec** [comment]
Hello. I would like to work on this issue. :-)
