### ISSUE TITLE
CLI args for explaining/printing the IR at various points

### ISSUE THREAD

**Issue by pdamme** [daphne-eu/daphne#403]
The DAPHNE compiler uses DaphneIR as the internal representation of a program, and performs various compiler passes, which optimize and lower the IR. To better understand the behavior of the DAPHNE compiler and runtime, it is very helpful to look at the IR at various stages, e.g., after property inference or after creating vectorized pipelines. We also call this feature EXPLAIN, in accordance with the well-known feature of database management systems.

To make this feature easily usable, `daphne` should have command-line arguments to turn on the printing of the IR after certain passes. We partially support this already. For instance, the [`DaphneUserConfig`](/daphne-eu/daphne/blob/main/src/api/cli/DaphneUserConfig.h) already contains various `explain_...` flags, and the [`DaphneIrExecutor`](/daphne-eu/daphne/blob/main/src/compiler/execution/DaphneIrExecutor.cpp) queries these flags to decide if a `PrintIRPass` shall be added after the respective stages. However, the flags in the `DaphneUserConfig` still need to be connected to the command-line arguments parsed in [`daphne.cpp`](/daphne-eu/daphne/blob/main/src/api/cli/daphne.cpp). So far, `daphne` only supports `--explain-kernels`, which maps to `DaphneUserConfig::explain_kernels`, and prints the IR after lowering to kernel calls.

**Task**
- This task is to ensure that the printing of the IR after all currently relevant DAPHNE compiler passes can be triggered by command-line arguments.
- In particular, we should support the passes already specified in `DaphneUserConfig`: `kernels`, `llvm`, `parsing`, `property_inference`, `sql`, `vectorized`, `obj_ref_mgnt`.
- There are two good options to implement this feature, please choose one of them:
  1. Add additional separate arguments like `--explain-kernels`, i.e., `--explain-llvm` etc. This should be quite straightforward, but will require the user to type the prefix `--explain` unnecessarily often when the IR shall be printed at multiple stages.
  2. Introduce a single argument `--explain`, which can be used like `--explain pass1,pass2,pass3` or `--explain pass1 pass2 pass3`, i.e., with a comma-separated or space-separated list. For the individual passes, only the values defined above shall be allowed. Since this feature is only about printing the IR (not about configuring the order of passes), the order of this list as well as potential duplicates would be irrelevant. [`cl::bits`](https://llvm.org/docs/CommandLine.html#collecting-options-as-a-set-of-flags) might be useful here.

**Hints**
- Have a look at the code files linked above.
- Have a look at the documentation on [DAPHNE configuration](/daphne-eu/daphne/blob/main/doc/Config.md) (although parts of that have already been implemented for this feature, as mentioned above)
- Have a look at the documentation of [LLVM's Command Line 2.0](https://llvm.org/docs/CommandLine.html) library, which we use for argument parsing.

**Comment by philipportner** [comment]
As previously discussed, I will be working on this issue.
