### ISSUE TITLE
LLVM checkout error

### ISSUE THREAD

**Issue by AhmedEleliemy** [daphne-eu/daphne#425]
I used the ./build.sh --cleanAll option to clean all the build directories.
This result in deleting the thirdparty folder. When I re-executed ./build.sh, the build failed.
it cannot checkout a specific commit.
The error is as follows.
Unable to checkout '4763c8c9e3c7ef2946fa575d5c6bf8dd7fb88639' in submodule path 'thirdparty/llvm-project'
error: The following untracked working tree files would be overwritten by checkout:
	.github/lockdown.yml
	clang-tools-extra/clangd/CSymbolMap.inc
	clang-tools-extra/clangd/StdSymbolMap.inc
	clang-tools-extra/clangd/include-mapping/cppreference_parser.py
	clang-tools-extra/clangd/include-mapping/gen_std.py
	clang-tools-extra/clangd/include-mapping/test.py
	clang-tools-extra/clangd/test/diagnostics.test
	clang-tools-extra/clangd/unittests/TestScheme.h
	clang-tools-extra/docs/clang-tidy/checks/abseil-duration-addition.rst
	clang-tools-extra/docs/clang-tidy/checks/abseil-duration-comparison.rst
	clang-tools-extra/docs/clang-tidy/checks/abseil-duration-conversion-cast.rst
	clang-tools-extra/docs/clang-tidy/checks/abseil-duration-division.rst
	clang-tools-extra/docs/clang-tidy/checks/abseil-duration-factory-float.rst
	clang-tools-extra/docs/clang-tidy/checks/abseil-duration-factory-scale.rst
	clang-tools-extra/docs/clang-tidy/checks/abseil-duration-subtraction.rst
	clang-tools-extra/docs/clang-tidy/checks/abseil-duration-unnecessary-conversion.rst
	clang-tools-extra/docs/clang-tidy/checks/abseil-faster-strsplit-delimiter.rst
	clang-tools-extra/docs/clang-tidy/checks/abseil-no-internal-dependencies.rst
	clang-tools-extra/docs/clang-tidy/checks/abseil-no-namespace.rst
	clang-tools-extra/docs/clang-tidy/checks/abseil-redundant-strcat-calls.rst
	clang-tools-extra/docs/clang-tidy/checks/abseil-str-cat-append.rst
	clang-tools-extra/docs/clang-tidy/checks/abseil-string-find-startswith.rst
	clang-tools-extra/docs/clang-tidy/checks/abseil-string-find-str-contains.rst
	clang-tools-extra/docs/clang-tidy/checks/abseil-time-comparison.rst
	clang-tools-extra/docs/clang-tidy/checks/abseil-time-subtraction.rst
	clang-tools-extra/docs/clang-tidy/checks/abseil-upgrade-duration-conversions.rst
	clang-tools-extra/docs/clang-tidy/checks/altera-id-dependent-backward-branch.rst
	clang-tools-extra/docs/clang-tidy/checks/altera-kernel-name-restriction.rst
	clang-tools-extra/docs/clang-tidy/checks/altera-single-work-item-barrier.rst
	clang-tools-extra/docs/clang-tidy/checks/altera-struct-pack-align.rst
	clang-tools-extra/docs/clang-tidy/checks/altera-unroll-loops.rst
	clang-tools-extra/docs/clang-tidy/checks/android-cloexec-accept.rst
	clang-tools-extra/docs/clang-tidy/checks/android-cloexec-accept4.rst
	clang-tools-extra/docs/clang-tidy/checks/android-cloexec-creat.rst
	clang-tools-extra/docs/clang-tidy/checks/android-cloexec-dup.rst
	clang-tools-extra/docs/clang-tidy/checks/android-cloexec-epoll-create.rst
	clang-tools-extra/docs/clang-tidy/checks/android-cloexec-epoll-create1.rst
	clang-tools-extra/docs/clang-tidy/checks/android-cloexec-fopen.rst
	clang-tools-extra/docs/clang-tidy/checks/android-cloexec-inotify-init.rst
	clang-tools-extra/docs/clang-tidy/checks/android-cloexec-inotify-init1.rst
	clang-tools-extra/docs/clang-tidy/checks/android-cloexec-memfd-create.rst
	clang-tools-extra/docs/clang-tidy/checks/android-cloexec-open.rst
	clang-tools-extra/docs/clang-tidy/checks/android-cloexec-pipe.rst
	clang-tools-extra/docs/clang-tidy/checks/android-cloexec-pipe2.rst
	clang-tools-extra/docs/clang-tidy/checks/android-cloexec-socket.rst
	clang-tools-extra/docs/clang-tidy/checks/android-comparison-in-temp-failure-retry.rst
	clang-tools-extra/docs/clang-tidy/checks/boost-use-to-string.rst
	clang-tools-extra/docs/clang-tidy/checks/bugprone-argument-comment.rst
	clang-tools-extra/docs/clang-tidy/checks/bugprone-assert-side-effect.rst
	clang-tools-extra/docs/clang-tidy/checks/bugprone-bad-signal-to-kill-thread.rst
	clang-tools-extra/docs/clang-tidy/checks/bugprone-bool-pointer-implicit-conversion.rst
	clang-tools-extra/docs/clang-tidy/checks/bugprone-branch-clone.rst
	clang-tools-extra/docs/clang-tidy/checks/bugprone-copy-constructor-init.rst
	clang-tools-extra/docs/clang-tidy/checks/bugprone-dangling-handle.rst
	clang-tools-extra/docs/clang-tidy/checks/bugprone-dynamic-static-initializers.rst
	clang-tools-extra/docs/clang-tidy/checks/bugprone-exception-escape.rst
	clang-tools-extra/docs/clang-tidy/checks/bugprone-fold-init-type.rst
	clang-tools-extra/doc
Do we need a specific commit?

**Comment by corepointer** [comment]
* The command ``build.sh --cleanAll`` does not remove the thirdparty directory. If you removed it by accident, you can restore it with ``git checkout thirdparty``
* As the error message says: "The following untracked working tree files would be overwritten by checkout"... If you move these files out of the way, the error message *should* go away. But maybe try my previous suggestion with restoring the lost thirdparty folder first.
* Yes, we need this specific commit because we rely on a certain state of the MLIR code.

**Comment by corepointer** [comment]
@AhmedEleliemy is this still an issue?

**Comment by AhmedEleliemy** [comment]
@corepointer sorry I missed your questions.  It is not an issue anymore. What I did is I deleted the thirdparty folder and then followed your suggestion git checkout thirdparty.  Thanks
