### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by corepointer** [daphne-eu/daphne#427]
As we continue to grow Daphne's code base, I think it's time to think about a good logging mechanism. To not invent that wheel for the 12345th time I strongly recommend introducing another external dependency and use a library for that. I've made a quick survey with my favorite search engine and came up with a [blog](https://www.sentinelone.com/blog/getting-started-quickly-cplusplus-logging/) that threatens to use Boost and this [list of logging libraries](https://reposhub.com/cpp-logging?sort_by=star) where the highest ranking entry looks promising. [sbdlog](https://github.com/gabime/spdlog/) is under MIT license, seems to have quite a user base according to github fork/star score and an active development community. It's fast©, supports multiple sinks and can be integrated in header only or compiled form (can be built using cmake, which fits nicely to our environment). 
Hoping for a fruitful and not too lengthy discussion ;-)

**Comment by MarcusParadies** [comment]
We are using spdlog internally in other larger C++ codebases since almost two years and liked it so far. Easy to use and quite flexible with many configuration parameters (e.g., sinks, threading, etc.). So overall recommendation from my side!

**Comment by corepointer** [comment]
Thank you for your feedback @MarcusParadies. 
I will give sbdlog a try and go forward with an initial integration to our code base. My thoughts about doing that:
* Making a log facility available to all parts of the code
* Support configuring the logger in our config file { verbosity levels, sinks }

After that initial functionality we will think about:
* logging in a distributed setting
* log configs for sub sections of DAPHNE ( e.g., configuring verbosity of compiler passes differently from local kernels or I/O etc)
