### ISSUE TITLE
Shape inference error with conv2d build-in function

### ISSUE THREAD

**Issue by aristotelis96** [daphne-eu/daphne#429]
When trying to use the build-in function `conv2d` the compiler returns:
`Pass error: shape inference cannot set the shape of op daphne.conv2DForward operand 1, since it is neither a matrix nor a frame`

This error can be reproduced when running `scripts/examples/dnn-conv2d.daph` or simply by the following script:
```
X = rand(5, 10240, 0.0, 256.0, 1.0, 1);
W = rand(64, 250, 0.0, 1.0, 1.0, 1);
b = rand(1, 64, 0.0, 1.0, 1.0, 1);

X_conv, Hout, Wout = conv2d(X, W, 5, 64, 32, 32, 5, 5, 1, 1, 1, 1, b);
```

**Comment by corepointer** [comment]
Fixed in c782d3b348dc820bb4e49dbb43aa04c89036ff68
