### ISSUE TITLE
SQLParser: Run Aggregation without grouping

### ISSUE THREAD

**Issue by tomschw** [daphne-eu/daphne#493]
Currently it is not possible to run a aggregation over a whole frame without grouping over some column in the frame when using SQL.

Not working code:
```
f = createFrame(
    [1, 10, 20],
    "a");

registerView("sample", f);

k = sql("select sum(sample.a) from sample;");

print(k);
```

Current workaround:
```
f = createFrame(
    [1, 10, 20],
    [0, 0, 0],
    "a", "temp");

registerView("sample", f);

k = sql("select sum(sample.a) from sample GROUP BY sample.temp;");

print(k);
```

**Comment by pdamme** [comment]
Thanks for reporting this bug, @tomschw. I can confirm it, the error message is `Pass error: Use of an aggregation function without a group clause`.

**Comment by pdamme** [comment]
Thanks for reporting this bug, @tomschw. I can confirm it, the error message is `Pass error: Use of an aggregation function without a group clause`.
