### ISSUE TITLE
SQLParser: Group by without aggregation clause not working

### ISSUE THREAD

**Issue by tomschw** [daphne-eu/daphne#494]
Currently, when running an SQL query which is just grouping some columns and outputting them, it throws the following error:

```daphne: /daphne/thirdparty/installed/include/mlir/IR/TypeRange.h:140: mlir::Type mlir::ValueTypeRange<ValueRangeT>::operator[](size_t) const [with ValueRangeT = mlir::OperandRange; size_t = long unsigned int]: Assertion `index < size() && "invalid index into type range"' failed.```

Sample code to reproduce error:
```
f = createFrame(
    [1, 10, 10, 20],
    "a");

registerView("sample", f);

k = sql("select sample.a from sample GROUP BY sample.a;");

print(k);
```

**Comment by pdamme** [comment]
Thanks for reporting this bug, @tomschw. I can confirm it. On my system, if even causes a segmentation fault.
