### ISSUE TITLE
Path changes of dependencies can lead to errors on already built projects

### ISSUE THREAD

**Issue by EricMier** [daphne-eu/daphne#507]
Currently we check if a dependency is already downloaded/installed via a flag-file. But this does not tackle path changes of dependencies on existing projects.

https://github.com/daphne-eu/daphne/blob/71ffea1179f4dbdedb621eb4ecf0f5db267e7472/build.sh#L572-L583

The build script checks only if the flag exists and does not do a fresh install in the updated path and therefore leads to errors while compiling assuming non existing files.

My suggestion is to add a virtual version to each dependency, which we increase each time a path updates. Alternatively we check the assumed paths, but that could lead into more overhead.

**Comment by corepointer** [comment]
Despite the build system getting increasingly complex, I think it's a nice idea :)

**Comment by corepointer** [comment]
This issue should have been closed automatically when we merged #508
