### ISSUE TITLE
Flexible matrix/frame literals in DaphneDSL

### ISSUE THREAD

**Issue by pdamme** [daphne-eu/daphne#523]
**Motivation:** DaphneDSL’s matrix literals are a convenient way to specify small matrices. For instance one can write `X = [1, 2, 3];` to get a (3x1) matrix containing the values 1, 2, and 3. This feature is very handy for writing small examples and test cases, and is also useful in complex scripts. Nevertheless, there are still a few points which could be made more convenient. Furthermore, besides matrices, DaphneDSL also supports frames, but there are no frame literals yet.

**Task:** This project is about adding more syntactic sugar around matrix and frame literals in DaphneDSLs. Implementation in C++. In particular, the following features should be supported:
- *Mixed value types:* Currently, all values in a matrix literal must be of the same value type. Ensure that matrix literals like `[1, 2.2]` or `[false, 3]` are allowed. The value type of the resulting matrix should be the most general of the values types of the elements. You can use `src/compiler/inference/TypeInferenceUtils.h` to determine the most general value type.
- *Expressions for the matrix elements:* Currently, all values in a matrix literal must themselves be literals, i.e., they must be known at parse-time. Ensure that the elements can be the results of complex expressions such as `[sqrt(2), 3.1, sum([1, 4, 2] + fill(x, 3, 1))]`. In such a case, the matrix cannot be constructed at parse-time. Instead, the expressions should be evaluated at runtime and operations should be generated to compose the overall matrix out of them.
- *Shape:* Currently, matrix literals are a linear list of *n* elements and result in a *(n x 1)* matrix, i.e., *n* rows and *1* column. Any other shape must be achieved by explicitly reshaping the matrix. For instance `reshape([1, 2, 3, 4], 2, 2)` creates a (2x2) matrix. This is a bit verbose; a notation like `[1, 2, 3, 4](2x2)` would be great.
- *Frame literals:* So far, DaphneDSL does not support frame literals. Instead, frames can be constructed from column matrices using the `createFrame()` built-in function, e.g., `createFrame([1, 2, 3], [1.1, -2.2, 3.3], "a", "b")`. As a first step, a simplification should be supported, such as `{"a": [1, 2, 3], "b": [1.1, -2.2, 3.3]}` (where the order of the columns is as specified).
- *Row-major frame literals:* As a second step, it should be possible to specify frames row-by-row, e.g., `{["a", "b"], [1, 1.1], [2, -2.2], [3, 3.3]}`. Note that each column of a frame can have its individual value type, which should be determined as the most general value types used in that column.

**Hints:**
- Have a look into the DaphneDSL parser in `src/parser/daphnedsl/` and specifically into the ANTLR grammar in `src/parser/daphnedsl/DaphneDSLGrammar.g4` and the core of the DaphneDSL parser in `src/parser/daphnedsl/DaphneDSLVisitor.cpp`.
- Take the examples above as rough ideas, slight syntactical deviations are fine, if required to make it work.

**Comment by AlexRTer** [comment]
I'd like to be assigned to this issue please

**Comment by pdamme** [comment]
Sure, go ahead!
