### ISSUE TITLE
Performance degradation due to "Sharing meta data among slices"

### ISSUE THREAD

**Issue by pdamme** [daphne-eu/daphne#526]
I've just noticed that the exeuction of all test cases by `./test.sh` suddenly takes much longer than usual on main. A quick investigation suggests that the recent commit 71ffea1179f4dbdedb621eb4ecf0f5db267e7472 might have introduced a performance problem.

As a concrete example: If I run the following command (which executes one of our test scripts directly):
```
bin/daphne --vec test/api/cli/vectorized/runEwBinary.daphne
```
it takes ~1.4 sec on my machine at the previous commit c782d3b348dc820bb4e49dbb43aa04c89036ff68. At the commit mentioned above, it takes ~50 sec on my machine. The non-vectorized execution does not seem to be affected. I haven't investigated the reasons in detail, but given that the commit in question seems to change something about data object meta data in the context of slicing, and slicing is heavily used in the vectorized engine, a causal relationship doesn't seem far fetched.

**Comment by corepointer** [comment]
Thx for spotting this. I'll look into it asap. The sharing of meta data among slices might very well introduce overhead as synchronization primitives were needed to protect the meta data object.
