### ISSUE TITLE
Casts in DaphneDSL

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#55]
In GitLab by @pdamme on Jun 11, 2021, 17:20

We need to be able to cast/convert between data objects and scalars of different types in DaphneDSL.

For instance:
- between different data objects (e.g. matrix and frame)
- between different value types of the same data type (e.g. matrix of float and matrix of int32)
- between data objects and scalars (e.g. making a scalar a 1x1 matrix, or making a 1x1 matrix a scalar)
- between scalars of different types

DaphneDSL needs a general syntax for that. It could be as simple as having built-in functions like `as.matrix(...)`. In any case, the result type of the DaphneIR `CastOp` to create must be reflected somehow, since it cannot be inferred from the arguments, of course.

**Comment by pdamme** [comment]
Parts of this feature have already been implemented (see, for instance, the `CastObj` and `CastSca` kernels, and the `CastExpr` in the DaphneDSL parser. However, two major points are still open:

**1. Casting between 1x1 matrix/frame and scalar**
 
A scalar can always be casted to a 1x1 matrix/frame of the same value type. A matrix/frame can be casted to a scalar, if its shape is 1x1; in that case the type of the scalar can be deduced from the matrix/frame.

We need:
- a kernel for casting from scalar to data object (`castObjSca`)
- a kernel for casting from data object to scalar (`castScaObj`)
- registration of these kernels in kernels.json
- unit test cases
- possibly ammendments to the DaphneDSL parser (see point 2)

**2. Better support in DaphneDSL**

We already have basic support for casts in DaphneDSL via the `as.` expression. This needs to be extended a bit to support the following cases:
- Specifying only the abstract data type, e.g., `as.scalar(x)`, `as.matrix(x)`, `as.frame(x)`. Here the value type (respectively frame column types) shall be retained from the input `x`, e.g., if `x` is a scalar of value type `f64`, then `as.matrix(x)` is of type `matrix<f64>` and `as.frame(x)` of type `frame<[f64]>`. As specified in point 1 above, casting to a scalar is not always possible and may cause a runtime error (or maybe a compiler error in connection with shape inference).
- Specifying only the value type, e.g., `as.f32(x)`, `as.ui8(x)`. Here the data type shall be retained from `x`, e.g., if `x` is of type `matrix<f64>` then `as.f32(x)` shall be of type `matrix<f32>` and if `x` is of type `frame<[si32, f64, f32]>` then `as.f32(x)` shall be of type `frame<[f32, f32, f32]>`.
- Specifying data type and value type, e.g., `as.scalar<si64>(x)`, `as.matrix<f32>(x)`, `as.frame<f32>(x)`, `as.frame<[f32, si64]>`. Here the input type is ignored and the output type is fully specified by the cast expression. For frames, individual column types can be specified (and the number of columns must match).

We also need script-level test cases for that.

**Please adapt existing scripts in `test/api/**` and `scripts/**` to these changes.**

**Comment by akroviakov** [comment]
Assigned to @akroviakov .

**Comment by akroviakov** [comment]
_If `x` is of type `frame<[si32, f64, f32]>` then `as.f32(x)` shall be of type `frame<[f32, f32, f32]>`._
Specifying column types when doing something like 
```
resType = mlir::daphne::FrameType::get(builder.getContext(), colTypes);
``` 
does not pass any info regarding types into the kernel implementation, since `Frame* res` is `nullptr` when viewed from the kernel. Neither do template arguments `CastObj<Frame, Frame>`.

Any other way to pass the value type would match a different cast template (e.g., cast to `DenseMatrix<VTRes>` or cast to some scalar `VTRes`), so it seems that to pass the value type inside a kernel we need to have an already created `Frame` with specified column types. 
Am I missing some other obvious way to pass the value type? If not, what would be the way to approach this?
