### ISSUE TITLE
Documentation for Profiling

### ISSUE THREAD

**Issue by tomschw** [daphne-eu/daphne#552]
I recently noticed some files and the command-line option for profiling support.
Depending on the extent of its functionality I would like to use it for benchmarks.
As I think it would also be useful for other users, documentation with the following information for new users would be very helpful:

- How to enable it
- What can it do and what can't it do (For example does it support calculating the runtime of each Kernel, does it support multiple runs etc.)
- Does it only support part of DAPHNE or everything?

**Comment by corepointer** [comment]
Initial work on this feature was contributed in PR #479 by @psomas. Maybe he can help.
