### ISSUE TITLE
Indexing test case violating fill assertion

### ISSUE THREAD

**Issue by corepointer** [daphne-eu/daphne#565]
https://github.com/daphne-eu/daphne/blob/505e2a31adfc5428dc318260c29a965e1b9d1576/test/api/cli/indexing/left_indexing_success_1.daphne#L223C27-L223C27

The referenced occurrence of fill() (and other occurrences) violate the assertion in Fill.h that state
``` cpp 
// from Fill.h line 54 & 55
        assert(numRows > 0 && "numRows must be > 0");
        assert(numCols > 0 && "numCols must be > 0");
```

Now this would be easily fixable if we the intended behavior was clear. From what I got in the C++ parts of DAPHNE the invoked constructor of DenseMatrix will take rowLowerIncl and rowUpperExcl (likewise for columns). This would require the fill statement to read ```fill(0, 1, 1);``` to yield anything. 

Furthermore, the indexing style in ```Xrc_08[:0, :0] = fill(0, 0, 0); ``` is not coming up in the documentation. What exactly should this statement do? According to the txt file that contains the expected output, this statement should have no effect (if I interpreted that correctly). Nevertheless, the correct behavior according to our assertion checks should be a test failure. 

Generally, this test case tests a lot of (undocumented) indexing examples which makes it hard to spot what is what in the output.

**Comment by pdamme** [comment]
Thanks for reporting this issue, @corepointer. **Those two assertions in `Fill.h` are wrong and need to be removed (feel free to do that).**

There is nothing wrong about a matrix/frame with zero rows and/or zero columns. For instance, applying a filter predicate could result in zero rows. Thus, it should be possible to create a 0x0 matrix using `fill()`, even though this is probably not very useful in practice.

The intended behavior of this (part of the) test case is to insert a 0x0 matrix into a 0x0 region of an existing matrix, which should, indeed, not have any effect. Again, surely not very useful in practice, but it's a corner case that may occur at some point and that should behave well.

Regarding the documentation: I hope this notation should become clear from the DaphneDSL language reference. Under "Statements"/"Assignment statement"/"Indexing" it reads that the "syntax is similar to (right) indexing in expressions". Under "Expressions"/"Indexing", there should be an exhaustive list of options for indexing. Let me know if you think we should extend/clarify anything there.

I agree that the DaphneDSL scripts for the indexing test cases are quite cluttered and that's not a good example to follow. However, I wanted to test a high number of cases/combinations, and with the current test infrastructure the only alternative would have been to create *a lot* of pairs of `.daphne` and `.txt` files. What I envision in the mid-term is a mechanism like the `SECTION`s in catch2, just in text files that we use for DaphneDSL script-level test.
