### ISSUE TITLE
Assertion fails in frame right-indexing by column name

### ISSUE THREAD

**Issue by corepointer** [daphne-eu/daphne#568]
This little test (adapted from ```createFrame_1.daphne```):

```
c1 = fill(123, 5, 1);
c2 = seq(100.5, 140.5, 10.0);
c3 = seq(-4, 4, 2);

f = createFrame(c1, c2, c3, "a", "b", "c");
print(f[,"a"]);
```

fails with:

```
/tmp/daphne/bin/daphne -config /tmp/daphne/UserConfig.json test/api/cli/operations/createFrame_1.daphne
daphne: /usr/local/include/mlir/IR/StorageUniquerSupport.h:173: static ConcreteT mlir::detail::StorageUserBase<ConcreteT, BaseT, StorageT, UniquerT, Traits>::get(mlir::MLIRContext*, Args ...) [with Args = {std::vector<mlir::Type, std::allocator<mlir::Type> >, long int, long int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*}; ConcreteT = mlir::daphne::FrameType; BaseT = mlir::Type; StorageT = mlir::daphne::detail::FrameTypeStorage; UniquerT = mlir::detail::TypeUniquer; Traits = {}]: Assertion `succeeded(ConcreteT::verify(getDefaultDiagnosticEmitFn(ctx), args...))' failed.

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

If ``"a"`` is changed to ``0`` the script runs just fine.

The issue surfaced now that I tried to run the test suite in debug mode (where the ``right_indexing_success_3.daphne`` test fails)

**Comment by pdamme** [comment]
Thanks for reporting. I can comfirm this bug. It happens in `Frame::verify()` (`src/ir/daphneir/DaphneDialect.cpp`), because one of the constraints we defined for a `FrameType` is violated. The root cause is an erroneously inferred return type in the DaphneDSL parser (there is a mistake in `DaphneDSLVisitor::applyRightIndexing()` (`src/parser/daphnedsl/DaphneDSLVisitor.cpp`).

**I will commit a fix tomorrow.**

**Comment by pdamme** [comment]
Short update: I'm working on it and am essentially done (fixing this bug revealed a few other "little" problems). Hope to finish it tomorrow.
