### ISSUE TITLE
String comparison is not implemented yet

### ISSUE THREAD

**Issue by bl1zzardx** [daphne-eu/daphne#581]
I am using the daphne-X86-64-v0.2 release. I tested the following:

`print(1==1);` results in output `1`.
`print("1"=="1");` results in an error:

> JIT session error: Symbols not found: [ _ewEq__char__char__char ]
JIT-Engine invocation failed: Failed to materialize symbols: { (main, { main, _mlir_main, _mlir__mlir_ciface_main, _mlir_ciface_main }) }Program aborted due to an unhandled Error:
Failed to materialize symbols: { (main, { main, _mlir_main, _mlir__mlir_ciface_main, _mlir_ciface_main }) }
[2023-08-04 12:50:35.723] [error] Got an abort signal from the execution engine. Most likely an exception in a shared library. Check logs!
[error]: Execution error: Returning from signal 6

**Comment by MarcusParadies** [comment]
I'd argue that this is not just a missing feature, but rather a bug in the earlier stages of the compilation. Imho unsupported operations should be handled before the actual compilation & execution (i.e., before the jitting) starts.

**Comment by corepointer** [comment]
This can be regarded as a bug or as a feature ;-) As a developer I argue more for the latter because nobody implemented the feature "check if the generated instruction actually exists and print out a more meaningful error message". Now that I think of it I'd rather advise against checking while compiling to not slow down that process. Once something has crashed we'd have all the time we need to create a meaningful output.

**Comment by m-birke** [comment]
missing string comparison hinders the usage of strings as script arguments for control flow switches

**Comment by philipportner** [comment]
I added a small patch for initial support of the `==` operator for strings. 
This should handle the use case of script argument strings for control flow switches @m-birke .

Examples:

* string with program argument

```
a = "foo";
if (a == $b)
```

* compare program string arguments
```
if ($a == $b)
```

* string constant comparison
```
print("1" ==  "1");
```

**Comment by pdamme** [comment]
Thanks for this patch @philipportner! I'm already using the string comparisons in the decision tree script now.
