### ISSUE TITLE
passing str variable to readFrame/readMatrix does not work

### ISSUE THREAD

**Issue by bl1zzardx** [daphne-eu/daphne#582]
I am using daphne-v0.2. Running this script below works for me, if I run the commented line for reading in the df. 
If I run it by using the passed `path` argument, it results in an Parser error.

```
def read_csv(path: str) {
    print(path);
    df = readMatrix(path);
    # df = readMatrix("/home/laberand/ifat_semiconductors/data/x.csv");
    print("Read csv at ", 0); print(path, 0);
}

read_csv("/home/laberand/ifat_semiconductors/data/x.csv");
```

Error:

> [error]: Parser error: basic_string::_M_construct null not valid

**Comment by bl1zzardx** [comment]
I forgot to mention that you can actually `print(path);` normally. Even casting it explicitly to a string via `print(as.str(path));` does not fix the error.

**Comment by corepointer** [comment]
Thx for reporting this. 
Quick pointer if anybody wants to solve this: We try to read file meta data while still parsing. So it looks like the parameter to the user defined function read_csv() is still a symbol and not really usable as a string. So this needs a not so trivial redesign of parsing readMatrix/readFrame.

**Comment by m-birke** [comment]
+1

**Comment by m-birke** [comment]
@bl1zzardx could you rename this issue? It is generally about the readX() functions and passing a str variable to them as argument. Also appears when using it directly within a script (so not a UDF)

**Comment by m-birke** [comment]
Lemme mention that this is a really blocking issue, to scale out with a DSL application one somehow at least needs a possibility to iterate over a dataset of files which necessarily are represented as variables

**Comment by bl1zzardx** [comment]
> @bl1zzardx could you rename this issue? It is generally about the readX() functions and passing a str variable to them as argument. Also appears when using it directly within a script (so not a UDF)

done.
