### ISSUE TITLE
how to return multiple values from a UDF?

### ISSUE THREAD

**Issue by bl1zzardx** [daphne-eu/daphne#583]
again daphne-v0.2: i created a UDF to simulate the train_test_split function from sklearn in python:

```
def train_test_split(x:matrix, y:matrix, rows:si64) { # -> (matrix, matrix, matrix, matrix)
    x_train = x[1:rows,]; 
    y_train = y[1:rows,];
    x_test = x[rows:,];
    y_test = y[rows:,];
    return x_train, y_train, x_test, y_test;
}
```

now I can of course run it, but I do struggle with the syntax to return multiple values. What would be the correct syntax for the return statement, to match the following call to the UDF?

`x_train, y_train, x_test, y_test = train_test_split(x, y, 10000);`

**Comment by pdamme** [comment]
Hi @bl1zzardx, in the v0.2 release, DaphneDSL didn't support UDFs with multiple return values yet. However, this feature has been added just now on main in 6db6d80d3d7a7ecf92e49fa1a3e40dc62066055e.

When you set the first line of your function definition as follows, then it should work out of the box.
```
def train_test_split(x:matrix, y:matrix, rows:si64) -> (matrix, matrix, matrix, matrix) {
```

**Comment by pdamme** [comment]
By the way: Please note that counting (rows and columns) starts at zero in DaphneDSL. Furthermore, the upper bound of right indexing expressions is exclusive. So you should probably write
```
    x_train = x[0:rows,]; 
    y_train = y[0:rows,];
    x_test = x[rows:,];
    y_test = y[rows:,];
```
for splitting the data into *rows* training rows and *#rows - rows* test rows (where *#rows* is the total number of rows in `X`/`y`).

**Comment by bl1zzardx** [comment]
as mentioned from @pdamme this has been fixed with https://github.com/daphne-eu/daphne/commit/6db6d80d3d7a7ecf92e49fa1a3e40dc62066055e. Thank you.
