### ISSUE TITLE
Hand crafted Frame does not accept variables?

### ISSUE THREAD

**Issue by bl1zzardx** [daphne-eu/daphne#584]
I can run this without a problem:

```
y = createFrame(
    [  0,   5],
    [750, 450],
    "d", "c");
print(y);
```

Yet, if i try it this way around, it gives me an error:
```
tn = 0;
fp = 12;
fn = 10;
tp = 5;

cf = createFrame(
     [tn, fp], 
     [fn, tp], 
     "neg", "pos");
print(cf);

```

> Parser error: <linenumber> mismatched input 'tn' expecting {']', 'true', 'false', INT_LITERAL, FLOAT_LITERAL, STRING_LITERAL}

**Comment by corepointer** [comment]
For the parser the statement in question is a [matrixLiteralExpr](https://github.com/daphne-eu/daphne/blob/1da02c8f2e98691ca6ca418d3ed4b672a8e6377e/src/parser/daphnedsl/DaphneDSLGrammar.g4#L99). What might work is changing the grammar from literal to expr and changing [the cpp code that handles this](https://github.com/daphne-eu/daphne/blob/1da02c8f2e98691ca6ca418d3ed4b672a8e6377e/src/parser/daphnedsl/DaphneDSLVisitor.cpp#L1242). I can't give it more time right now and will circle back to it if it isn't picked up by one of our parser people (TUD, TUB and a few students to be git-blamed here :wink: )  in the meantime.

**Comment by MarcusParadies** [comment]
According to the doc, matrix literals (as of now), must only consist of actual literals and no expressions.

Something like this would probably work right now, but yeah, not pretty... 

```
tn = 0;
fp = 12;
fn = 10;
tp = 5;

m1 = fill(0,1,2);
m1[0,1] = fill(tn, 1, 1);
m1[0,0] = fill(fp, 1, 1);

m2 = fill(0,1,2);
m2[0,1] = fill(fn, 1, 1);
m2[0,0] = fill(tp, 1, 1);

cf = createFrame(reshape(m1,2,1), reshape(m2,2,1), "neg", "pos");
print(cf);
```

**Comment by pdamme** [comment]
Yes, DaphneDSL matrix literals support only literal numbers for their elements so far. There is a issue about more flexible matrix and frame literals: #523.

Yes, workarounds like the one by @MarcusParadies can be used. It may even be slightly simpler as follows:
```
tn = 0;
fp = 12;
fn = 10;
tp = 5;

c1 = fill(0,2,1); # column 1
c1[0,] = as.matrix(tn);
c1[1,] = as.matrix(fn);

c2 = fill(0,2,1); # column 2
c2[0,] = as.matrix(fp);
c2[1,] = as.matrix(tp);

cf = createFrame(c1, c2, "neg", "pos");
print(cf);
```
But ultimately, variables and expression shall be valid for the elements of matrix and frame literals.

-----

@bl1zzardx Please note that the matrices passed to `createFrame()` are the columns of the frame. With the column labels you assigned, it seems a bit like you meant them to be the rows.

**Comment by bl1zzardx** [comment]
thanks for the mentioned work-arounds. I incorporated one of them in my scripts, i will leave this open, because you might want to take a look at it again, if you try to solve https://github.com/daphne-eu/daphne/issues/523.
