### ISSUE TITLE
Parser error default ValueType Meta Data Frame

### ISSUE THREAD

**Issue by tomschw** [daphne-eu/daphne#591]
The [documentation ](https://github.com/daphne-eu/daphne/blob/main/doc/FileMetaDataFormat.md)for the meta data files mentions that data frame files should support a default value type.
If however I use the following meta data file for a frame: 
```
{
  "numRows": 2,
  "numCols": 2,
  "valueType": "ui64",
  "schema": [
    {
      "label": "foo",
      "valueType": ""
    },
    {
      "label": "bar",
      "valueType": ""
    }
  ]
}
```
and use readFrame in a DAPHNE script I receive the following error:
`Parser error: ParserUtils::mlirTypeForCode: unknown value type code`

The error goes away if I actually set the value type for each label it works just fine.

**Comment by corepointer** [comment]
Thx for reporting. I can confirm that this is neither tested nor parsed correctly.
