### ISSUE TITLE
Default logger doesn't log any information on a higher level than 'error'

### ISSUE THREAD

**Issue by MarcusParadies** [daphne-eu/daphne#593]
The default logger doesn't log any information on a higher level than 'error'.

Since the default logger should in any case at least log on level 'error', there is a special piece of code that ensures that. However, the condition of the check is not correct (and should be the opposite). If the log-level is lower (i.e., larger enum val (!)), the log level should be set to 'error'.

**Comment by corepointer** [comment]
You are absolutely right - thx for pointing that out :+1: 
I'm struggling with the default logger as well at the moment (segfaults everything when running in cuda release mode).

**Comment by MarcusParadies** [comment]
PR is already up! #594
