### ISSUE TITLE
Including contribution in existing code base results in build error "error: reference to 'map' is ambiguous"

### ISSUE THREAD

**Issue by Thenz** [daphne-eu/daphne#597]
I am aiming for a successful build in which my code contribution is included, but not yet called. Unfortunately, doing so in the two files that are of relevance for my particular issue, results in an "error: reference to 'map' is ambiguous".  

The file I am trying to include lies in daphne/src/util/ .

I am building the standard BASE image for Daphne development, as is defined in build-containers.sh, while each of the remaining images are commented out. Building without including my contribution succeeds perfectly well. I am running on Ubuntu 22.04. 

![Head of build-error](https://github.com/daphne-eu/daphne/assets/32069037/1ce6f6b4-2531-4c36-bb0d-5283d3a5f5ee)

![relevant part of build-containers.sh](https://github.com/daphne-eu/daphne/assets/32069037/66fe1469-3e1d-4dc2-8e8d-f9782e0365c0)

While I have been trying to, I can't yet exclude having made a silly mistake. Feel free to request any additional information that might help to resolve this issue. Thanks.

**Comment by MarcusParadies** [comment]
Did you do 

`using namespace std;`

anywhere in your code?

**Comment by Thenz** [comment]
Yeah, right below the imports.

**Comment by MarcusParadies** [comment]
Better use truncated namespace imports (see [here](https://saturncloud.io/blog/why-is-using-namespace-std-considered-bad-practice/#:~:text=Finally%2C%20%E2%80%9Cusing%20namespace%20std%3B,name%20collisions%20and%20unexpected%20behavior.) for details).

**Comment by Thenz** [comment]
Will update my code, thanks for the info.
