### ISSUE TITLE
[discussion] Daphne Lib Containers pip

### ISSUE THREAD

**Issue by BacchusX1** [daphne-eu/daphne#599]
I would like to have an installer (e.g. pip) installed in the container's in order to quickly adapt to an existing python workflow by installing all necessary libraries.
What do you think about it ?

**Comment by corepointer** [comment]
In the daphne-dev image, you can use virtualenv to create your environment. That also gives you pip. Use it like this:
``` bash
# virtualenv venv
# source venv/bin/activate
(venv) # pip install matplotlib
```

**Comment by BacchusX1** [comment]
Ok then virtual environments are the way to go, thanks!
