### ISSUE TITLE
Enable printing of IR

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#6]
In GitLab by @pdamme on Mar 15, 2021, 21:58

Instead of or in addition to JIT-compiling and executing the given DaphneDSL program, being able to print the intermediate representation of the program would be very helpful to understand the IR, its use, the impact of optimization passes, etc. The IR could be printed in different stages, e.g., directly after parsing the DSL program, after all or certain optimization/rewrite/lowering passes higher than LLVM, or after the lowering to LLVM.

Ideally, there should be command line arguments controlling whether and what IR to print. MLIR/LLVM already has some facilities for argument parsing that could/should be reused.

**Comment by corepointer** [comment]
Stumbled across this while checking if a bug in printing was already reported :D 
Imho this can be closed since the introduction of ```--explain=``` CLI flag of DAPHNE. But since you're the original author of this @pdamme, please reopen if there's more to it.

**Comment by pdamme** [comment]
I completely agree with you, this issue has already been addressed.
