### ISSUE TITLE
DaphneLib Complex Computation exp(matrix)

### ISSUE THREAD

**Issue by BacchusX1** [daphne-eu/daphne#602]
function like np.exp(x) which returns element-wise exponential of x

`kernel_matrix = np.exp(norm * gamma)`

**Comment by corepointer** [comment]
Try this:
``print(exp(1));``
Also works for matrices.
In [this documentation page](https://daphne-eu.github.io/daphne/DaphneDSL/Builtins/) you'll find more on currently supported builtin functions.

**Comment by BacchusX1** [comment]
> Try this: `print(exp(1));` Also works for matrices. In [this documentation page](https://daphne-eu.github.io/daphne/DaphneDSL/Builtins/) you'll find more on currently supported builtin functions.

Are all build in functions from DaphneDSL supported on python side using DaphneLIB ?

**Comment by pdamme** [comment]
Many of the DaphneDSL built-in functions (including `exp()`)  are not supported in DaphneLib yet, which limits the usefulness of DaphneLib at the moment. I will work on it today.

**Comment by corepointer** [comment]
I thought I checked that this is about DaphneDSL and not DaphneLib. My bad :see_no_evil: :man_facepalming:

**Comment by pdamme** [comment]
No worries ;) .
