### ISSUE TITLE
Transpose and MatMul return wrong result when using vectorized engine

### ISSUE THREAD

**Issue by aristotelis96** [daphne-eu/daphne#611]
The following script returns the expected result:
```
A = rand(5, 5, 0.0, 1.0, 1.0, 1);
B = rand(1, 5, 0.0, 1.0, 1.0, 2);

tB = t(B);
print(A @ tB);
```
Output:
```
DenseMatrix(5x1, double)
1.73466
1.79427
1.24948
1.70799
1.49671
```
However, when using the vectorized engine (`--vec` flag) the output is wrong, or sometimes seems to be uninitialized values (or `-nan`).

Notes:
- Adding the `--no-phy-op-selection` does not seem to solve the issue.
- Not sure if this a known issue, #447 seems relevant, though it mentions transposition of left-hand-side operand.

**Comment by corepointer** [comment]
Thx for reporting it. Vectorizing this results in dot products for the worker threads and this dot operation handles the increment (rowskip) incorrectly. iFixit and add your test case.
