### ISSUE TITLE
Support missing elementwise unary functions in elementwise unary kernels.

### ISSUE THREAD

**Issue by pdamme** [daphne-eu/daphne#614]
DaphneDSL supports several elementwise unary functions (both on matrices and scalars), such as `sqrt` and `sin`. However, some of these functions are not supported by the respective kernels `EwUnaryMat` and `EwUnarySca` yet (see `src/runtime/local/kernels/EwUnary*.h`).

This task is to add the following missing elementwise unary functions and to extend the existing unit test cases accordingly. Furthermore, please search for `(see #614)` in the code base, since I highlighted a few relevant spots that way:
- `ln`
- `sin`
- `cos`
- `tan`
- `sinh`
- `cosh`
- `tanh`
- `asin`
- `acos`
- `atan`

**Comment by AlexRTer** [comment]
Hi, I would like to be assigned to this issue

**Comment by pdamme** [comment]
Sure, go ahead!
