### ISSUE TITLE
RandomForest implementation 

### ISSUE THREAD

**Issue by bl1zzardx** [daphne-eu/daphne#621]
So for my project I have been using decision trees a lot. [RandomForests ](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html) are also used as a feature selection method because they are rather unbiased due to their nature. I would really welcome an implementation of decision trees and furthermore RandomForests in DaphneDSL, so I can use them with just a function call.

**Comment by divjakm** [comment]
I'm tempted to try to implement this. First the decision tree (the standard CART variant) in Daphne DSL and then extension into Random Forest. But I'm no expert in this field, the languange is still very much in development and I can't work full time on this. So it would be a bit of a challenge, and it would probably take quite some time. A month perhaps? Would this still be feasible for you, or do you perhaps already have somebody else working on this?

**Comment by corepointer** [comment]
Afaik, @pdamme has been working on this. There's a [branch](https://github.com/daphne-eu/daphne/tree/decisionTrees_randomForests) with a few commits of a WIP port from SystemDS' DML implementation. There's quite a number of *TODO*s in them. I've been looking into implementing the stop function that is mentioned in several places, as I'm further ramping up on my MLIR skills :P

**Comment by divjakm** [comment]
Aha, ok. I was thinking of doing this in the Daphne DSL language, but it's probably  better to implement it as a part of Daphne data structures in C++.

**Comment by corepointer** [comment]
The implementation of the random forests is done in DDSL. But it seems that not all of the required functionality is available in the language (e.g., the stop function). Ops like these need a C++ implementation.

**Comment by divjakm** [comment]
OK, I found it now. It's in scripts/algorithms/. Thanks!

**Comment by corepointer** [comment]
You're welcome :bow: 
Pro tip: Look at the commit history. There all modified files and their paths are listed. Ideally the commit message tells you what was changed too =) In our case here, the two latest commits in that branch have the modifications that add the random forests :evergreen_tree::evergreen_tree::evergreen_tree:

**Comment by bl1zzardx** [comment]
@pdamme, is there same progress in the background on this?

**Comment by pdamme** [comment]
Hi @bl1zzardx! Yes, there is some progress, but it is unfortunately hard to tell when the scripts will be ready to use...

I have continued the work on the decision tree and random forest scripts recently. I'm meanwhile (with some local changes that I still need to push) at a point where the training part of decision tree runs in DAPHNE and random forest runs at least for certain hyper parameters (e.g., sampling features or examples can still cause problems). Unfortunately, larger input datasets still causes DAPHNE compiler error, I'm currently trying to find out what's going wrong there. For the scoring part of decision trees, the DAPHNE compilation currently does not seem to terminate. Furthermore, the outputs of all those scripts still need to be compared to SystemDS (at least manually for a few cases), to see if the output makes sense at all.

**Comment by bl1zzardx** [comment]
hi, thanks for the answer, I can see that there is a lot of work that has to go into this feature. And also thanks for putting the effort in.

**Comment by pdamme** [comment]
Hi @bl1zzardx, there are initial implementations of decision trees and random forests on the main branch now (manually translated from Apache SystemDS's DML built-in functions). You can find usage examples in the test cases (`test/api/cli/algorithms/decisionTreeRealData2.daphne` and `test/api/cli/algorithms/decisionTreeRealData3.daphne`).

Sorry again that it took so long. These were the most complex DaphneDSL scripts we have tried so far and, unsurprisingly, they revealed several missing features and bugs in the system, which needed to be fixed or worked around. Consequently, the usability of the system has improved significantly recently and we are clearly aware of several more things to improve now, and working on them.

So far, the focus was on making decision trees and random forests work, first of all. They have not been optimized for runtime performance yet.

Feel free to try them, and let us know in case you encounter any difficulties.

**Comment by bl1zzardx** [comment]
thanks again for implementing it - i will give it a try now! ^^
