### ISSUE TITLE
Error creating matrix from function arguments?

### ISSUE THREAD

**Issue by divjakm** [daphne-eu/daphne#622]
I don't know whether I'm doing something wrong or is there a Daphne DSL error in this example:

```
def test (a:f64, b:f64, c:f64)
{
    //A = a + b + c;          // works
    //A = [1.0, 2.0, 3.0];    // works
    A = [a, b, c];        // error
    print(A);
}
test (1.0, 2.0, 3.0);
```
I get the following error:
`Parser error: test7.daph:40:9 mismatched input 'a' expecting {']', 'true', 'false', INT_LITERAL, FLOAT_LITERAL, STRING_LITERAL}`

Any help is very appreciated!

**Comment by pdamme** [comment]
Hi @divjakm, so far, matrix literals in DaphneDSL only support parse-time *literals* for their elements, while *expressions* are not supported yet (not even simple ones like just a variable).

However, we definitely want to support expressions for the elements, and there is an issue for that #523. We would highly welcome a pull request for that issue, from anyone who would like to help.

This missing feature has been reported before in #584, where you can also find a workaround. Put shortly, you could currently do something like `A = rbind(rbind(as.matrix(a), as.matrix(b)), as.matrix(c));` or `A = fill(0.0, 3, 1); A[0, ] = as.matrix(a); A[1, ] = as.matrix(b); A[2, ] = as.matrix(c);`. But ultimately, `A = [a, b, c];` will work.
