### ISSUE TITLE
Kernel for `extractCol`-operation for `DenseMatrix`

### ISSUE THREAD

**Issue by daphne-eu** [daphne-eu/daphne#65]
In GitLab by @pdamme on Jun 11, 2021, 19:29

We need a specialization of this kernel for `DenseMatrix`. The selected columns should be specified by min/max (a special case is when min equals max). Alternatively, they could be specified by a nx1 column matrix containing the positions of the columns to extract.

**Comment by pdamme** [comment]
This issue was rephrased as #193 and was addressed 2 years ago in c33f2128d91b65a0963f6666f6265a08189ed833. Thus, I close it now.
