### ISSUE TITLE
Expired GPG Key

### ISSUE THREAD

**Issue by Linux-Alex** [daphne-eu/daphne#654]
The GPG key associated with the signature in the file `daphne-X86-64-v0.2-bin.tgz.asc` has expired. This prevents successful verification using the `gpg --verify` command.

**Terminal output:**
```
aleks@kde-tester:~$ gpg --verify daphne-X86-64-v0.2-bin.tgz.asc
gpg: assuming signed data in 'daphne-X86-64-v0.2-bin.tgz'
gpg: Signature made Sun 30 Jul 2023 11:48:26 PM UTC
gpg:                using RSA key 7A87EBBC332C11D7A940689518E8C09D537D5346
gpg: Good signature from "Mark Dokter <mark@dokter.cc>" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: 761B 1BF8 6688 78B6 2054  4D37 2F85 DD25 B28F 8F4D
     Subkey fingerprint: 7A87 EBBC 332C 11D7 A940  6895 18E8 C09D 537D 5346
```

**Comment by corepointer** [comment]
Thanks @Linux-Alex for spotting this issue. I had the key expiry date fixed locally but did not update it in my GitHub account. It was up to date on keys.openpgp.org though. May I ask where you retrieved my key from?

Regards, Mark
