### ISSUE TITLE
Float literals in scientific notation

### ISSUE THREAD

**Issue by pdamme** [daphne-eu/daphne#659]
Currently, DaphneDSL supports float literals only of the form `123.4567`, plus some special cases like `inf` and `nan`. However, floating-point numbers are also commonly expressed in the scientific notation, e.g. `1.234567e2`. This notation is especially convenient for writing very small or very large numbers, e.g., `10000` becomes `1e5` and `0.000001` becomes `1e-6` (there could be far more zeros).

This task is to support the scientific notation in DaphneDSL, in addition to the currently supported floating-point notations.

**Hints:**
- Find out what syntax and potential corner cases are supported in other programming languages, such as Python, R, C++, etc., and implement that in DAPHNE.
- Search for `#659` in the code base (especially in `scripts/algorithms/`), several points where the scientific notation should be used are marked that way.

**Comment by AlexRTer** [comment]
I would like to work on this issue.

**Comment by pdamme** [comment]
Thanks, go ahead!

**Comment by AlexRTer** [comment]
Are there any plans for adding digit separators to DaphneDSL yet? I think they would further improve readability for large numbers just like scientific notation does in some cases. Specifically, I'm thinking of adding `_` and `'` (e.g. `1_000_000` and `1'000'000`) which are used e.g. by Python and C++.

**Comment by pdamme** [comment]
As far as I know, there were no concrete plans for digit separators yet, but it sounds like a good idea to me. Feel free to implement that as well, if it doesn't take too much time.
