### ISSUE TITLE
Dockerhub Daphne Container: error while loading shared libraries: libxml2.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bl1zzardx** [daphne-eu/daphne#664]
Hi,

I tried the [currently newest daphne container](daphneeu/daphne:2023-12-20_X86-64_BASE_ubuntu20.04) and got this error, while trying to execute a script with daphneDSL:

- /usr/local/bin/daphne: error while loading shared libraries: libxml2.so.2: cannot open shared object file: No such file or directory

here is what I did:

- start docker service: sudo service docker start
- pull latest image: docker pull daphneeu/daphne:latest_X86-64_BASE
- list all images: docker images
- tag the previous image as known_to_work: docker tag <image id> daphneeu/daphne:known_to_work
- alias ionbeam_latest='docker run --rm -w /daphne -v "/home/laberand/daphne_work/ifat_semiconductors:/ifat_semiconductors" -e GID=$(id -g) -e USER=$(id -n -u) -e UID=$UID daphneeu/daphne:latest_X86-64_BASE /ifat_semiconductors/daphne/ionbeamtuning.daph'
- running ionbeam_latest yields/throws the above mentioned error

yet, when running it with some previous dockerhub image, which I tagged with daphne:known_to_work, the same scripts runs through without errors.

Additionally, just recently the RandomForest implementation was added. Therefore, I would like to request an updated dockerhub image, which fixes the above error (could of course be on user-side as well) and also includes the randomforest implementation. 

Many thanks and best regards,
Andreas

**Comment by auge** [comment]
this can usually be fixed by installing `libxml2` (apt install libxml2)
however, it's not so trivial in this container … I managed to get it run as following:

* `docker run -it --entrypoint /bin/bash daphneeu/daphne:latest_X86-64_BASE`
within container:
* `apt update && apt install libxml2`

KR, Benjamin

**Comment by bl1zzardx** [comment]
> this can usually be fixed by installing `libxml2` (apt install libxml2) however, it's not so trivial in this container … I managed to get it run as following:
> 
> * `docker run -it --entrypoint /bin/bash daphneeu/daphne:latest_X86-64_BASE`
>   within container:
> * `apt update && apt install libxml2`
> 
> KR, Benjamin

hi, thanks for the suggestion, i tried it. Yet, it does not finish the process, 
<details>
<summary>complaining about ".. is not a symbolic link".</summary>

logs:
docker run -it --entrypoint /bin/bash daphneeu/daphne:latest_X86-64_BASE
root@be729dda84ab:/# apt update 
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:5 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [3318 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1275 kB]      
Get:8 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [1183 kB]
Get:9 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]         
Get:10 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]          
Get:11 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [29.7 kB]
Get:12 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [3415 kB]        
Get:13 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1477 kB]     
Get:14 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [3468 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [32.4 kB]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [3891 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [55.2 kB]
Get:18 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [28.6 kB]
Fetched 30.3 MB in 5s (6577 kB/s)                           
Reading package lists... Done
Building dependency tree       
Reading state information... Done
13 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@be729dda84ab:/# apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  base-files libgnutls30 libpam-modules libpam-modules-bin libpam-runtime libpam0g libsqlite3-0 libssl1.1 libsystemd0 libudev1 login passwd tzdata
13 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 4817 kB of archives.
After this operation, 18.4 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 base-files amd64 11ubuntu5.8 [60.3 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 login amd64 1:4.8.1-1ubuntu5.20.04.5 [220 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libpam0g amd64 1.3.1-5ubuntu4.7 [55.4 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libpam-modules-bin amd64 1.3.1-5ubuntu4.7 [41.2 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libpam-modules amd64 1.3.1-5ubuntu4.7 [261 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libsystemd0 amd64 245.4-4ubuntu3.23 [268 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libpam-runtime all 1.3.1-5ubuntu4.7 [37.3 kB]
Get:8 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libudev1 amd64 245.4-4ubuntu3.23 [75.6 kB]
Get:9 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 passwd amd64 1:4.8.1-1ubuntu5.20.04.5 [797 kB]
Get:10 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libgnutls30 amd64 3.6.13-2ubuntu1.10 [827 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libsqlite3-0 amd64 3.31.1-4ubuntu0.6 [549 kB]
Get:12 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libssl1.1 amd64 1.1.1f-1ubuntu2.22 [1323 kB]
Get:13 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 tzdata all 2023d-0ubuntu0.20.04 [303 kB]
Fetched 4817 kB in 1s (4459 kB/s) 
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 8346 files and directories currently installed.)
Preparing to unpack .../base-files_11ubuntu5.8_amd64.deb ...
Unpacking base-files (11ubuntu5.8) over (11ubuntu5.7) ...
Setting up base-files (11ubuntu5.8) ...
Installing new version of config file /etc/update-motd.d/10-help-text ...
(Reading database ... 8346 files and directories currently installed.)
Preparing to unpack .../login_1%3a4.8.1-1ubuntu5.20.04.5_amd64.deb ...
Unpacking login (1:4.8.1-1ubuntu5.20.04.5) over (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up login (1:4.8.1-1ubuntu5.20.04.5) ...
(Reading database ... 8346 files and directories currently installed.)
Preparing to unpack .../libpam0g_1.3.1-5ubuntu4.7_amd64.deb ...
Unpacking libpam0g:amd64 (1.3.1-5ubuntu4.7) over (1.3.1-5ubuntu4.6) ...
Setting up libpam0g:amd64 (1.3.1-5ubuntu4.7) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
(Reading database ... 8346 files and directories currently installed.)
Preparing to unpack .../libpam-modules-bin_1.3.1-5ubuntu4.7_amd64.deb ...
Unpacking libpam-modules-bin (1.3.1-5ubuntu4.7) over (1.3.1-5ubuntu4.6) ...
Setting up libpam-modules-bin (1.3.1-5ubuntu4.7) ...
(Reading database ... 8346 files and directories currently installed.)
Preparing to unpack .../libpam-modules_1.3.1-5ubuntu4.7_amd64.deb ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Unpacking libpam-modules:amd64 (1.3.1-5ubuntu4.7) over (1.3.1-5ubuntu4.6) ...
Setting up libpam-modules:amd64 (1.3.1-5ubuntu4.7) ...
(Reading database ... 8346 files and directories currently installed.)
Preparing to unpack .../libsystemd0_245.4-4ubuntu3.23_amd64.deb ...
Unpacking libsystemd0:amd64 (245.4-4ubuntu3.23) over (245.4-4ubuntu3.22) ...
Setting up libsystemd0:amd64 (245.4-4ubuntu3.23) ...
(Reading database ... 8346 files and directories currently installed.)
Preparing to unpack .../libpam-runtime_1.3.1-5ubuntu4.7_all.deb ...
Unpacking libpam-runtime (1.3.1-5ubuntu4.7) over (1.3.1-5ubuntu4.6) ...
Setting up libpam-runtime (1.3.1-5ubuntu4.7) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
(Reading database ... 8346 files and directories currently installed.)
Preparing to unpack .../libudev1_245.4-4ubuntu3.23_amd64.deb ...
Unpacking libudev1:amd64 (245.4-4ubuntu3.23) over (245.4-4ubuntu3.22) ...
Setting up libudev1:amd64 (245.4-4ubuntu3.23) ...
(Reading database ... 8346 files and directories currently installed.)
Preparing to unpack .../passwd_1%3a4.8.1-1ubuntu5.20.04.5_amd64.deb ...
Unpacking passwd (1:4.8.1-1ubuntu5.20.04.5) over (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up passwd (1:4.8.1-1ubuntu5.20.04.5) ...
(Reading database ... 8346 files and directories currently installed.)
Preparing to unpack .../libgnutls30_3.6.13-2ubuntu1.10_amd64.deb ...
Unpacking libgnutls30:amd64 (3.6.13-2ubuntu1.10) over (3.6.13-2ubuntu1.9) ...
Setting up libgnutls30:amd64 (3.6.13-2ubuntu1.10) ...
(Reading database ... 8346 files and directories currently installed.)
Preparing to unpack .../libsqlite3-0_3.31.1-4ubuntu0.6_amd64.deb ...
Unpacking libsqlite3-0:amd64 (3.31.1-4ubuntu0.6) over (3.31.1-4ubuntu0.5) ...
Preparing to unpack .../libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb ...
Unpacking libssl1.1:amd64 (1.1.1f-1ubuntu2.22) over (1.1.1f-1ubuntu2.20) ...
Preparing to unpack .../tzdata_2023d-0ubuntu0.20.04_all.deb ...
Unpacking tzdata (2023d-0ubuntu0.20.04) over (2023c-0ubuntu0.20.04.2) ...
Setting up libssl1.1:amd64 (1.1.1f-1ubuntu2.22) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Setting up libsqlite3-0:amd64 (3.31.1-4ubuntu0.6) ...
Setting up tzdata (2023d-0ubuntu0.20.04) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype

Current default time zone: 'Etc/UTC'
Local time is now:      Wed Feb 28 06:55:33 UTC 2024.
Universal Time is now:  Wed Feb 28 06:55:33 UTC 2024.
Run 'dpkg-reconfigure tzdata' if you wish to change it.

Processing triggers for libc-bin (2.31-0ubuntu9.14) ...
/sbin/ldconfig.real: /usr/local/lib/libmpi_usempif08.so.40 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libmpi_mpifh.so.40 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libmca_common_monitoring.so.50 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libompitrace.so.40 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libopenblas.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libmca_common_ompio.so.41 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libmpi.so.40 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libparquet.so.1300 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libmca_common_dstore.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libpapi.so.7.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libarrow.so.1300 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libmca_common_sm.so.40 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libsde.so is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libopen-rte.so.40 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libopen-pal.so.40 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libpfm.so.4 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libmpi_usempi_ignore_tkr.so.40 is not a symbolic link

root@be729dda84ab:/# 

</details>

**Comment by corepointer** [comment]
Hi!
Thanks for spotting and reporting this @bl1zzardx and thanks for helping out @auge!
Indeed, the libxml2 is missing in the daphne image:
```
root@5e00b4f614cf:/# ldd /usr/local/bin/daphne 
        linux-vdso.so.1 (0x00007ffd43ae3000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1fe82a0000)
[...]
        libxml2.so.2 => not found
```

And indeed, the suggested fix from @auge helps. After installing, the same command as above shows:
```
root@5e00b4f614cf:/# ldd /usr/local/bin/daphne 
[...]
        libxml2.so.2 => /lib/x86_64-linux-gnu/libxml2.so.2 (0x00007ff82e4db000)
        libicuuc.so.66 => /lib/x86_64-linux-gnu/libicuuc.so.66 (0x00007ff82e2f5000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007ff82e2ca000)
        libicudata.so.66 => /lib/x86_64-linux-gnu/libicudata.so.66 (0x00007ff82c809000)
```

So this should work :) Please ignore the errors from the installation command.

Also a quick 
```
root@5e00b4f614cf:/# /usr/local/bin/daphne --version
DAPHNE Version 0.2
An Open and Extensible System Infrastructure for Integrated Data Analysis Pipelines
https://github.com/daphne-eu/daphne
```
looks like this fix is working. 

I will update the Docker images of course. In the meantime please use this quick fix.

Regards, Mark

**Comment by bl1zzardx** [comment]
thanks, works like a charm.
