### ISSUE TITLE
`seq()` DaphneDSL built-in: Make `inc` argument optional

### ISSUE THREAD

**Issue by pdamme** [daphne-eu/daphne#666]
The `seq()` built-in function in DaphneDSL creates an increasing sequence of numbers from a given `start` to a given `end` in increments of a given `inc`. In fact, the increment is very often `1`, so for convenience, it would be great to make the increment an optional argument.

This can and should be done purely at the DSL level (no need for a deeper integration into DaphneDSL or the kernels). The change can be implemented in `src/parser/daphnedsl/DaphneDSLBuiltins.cpp`. It should be accompanied by some script-level test cases.

**Comment by saminbassiri** [comment]
Hi, please assign me to this issue.

**Comment by pdamme** [comment]
Sure, go ahead!
