### ISSUE TITLE
Unary minus operator in DaphneDSL

### ISSUE THREAD

**Issue by pdamme** [daphne-eu/daphne#667]
DaphneDSL does not support the typical unary minus operator yet. While a minus can be part of a numeric literal (such as `y = -1.23`), one cannot use a unary minus in expressions yet (such as `y = -x` or `y = -(sin(x) ^ 1.23`). There is a workaround (such as `y = 0 - x`), but we should not require that, since it's quite inconvenient.

Solving this issue requires:
- changes to the DaphneDSL parser
- a new elementwise unary operator for *minus*
- adding some script-level test cases

**Comment by corepointer** [comment]
This is a duplicate of #560 and half-way implemented in PR #560.
