### ISSUE TITLE
DaphneDSL `write()` handles views incorrectly

### ISSUE THREAD

**Issue by pdamme** [daphne-eu/daphne#669]
The following DaphneDSL script should write the second column of a small matrix to a file:
```R
# Create (3x2) matrix [[1, 2], [3, 4], [5, 6]].
X = reshape(seq(1, 6, 1), 3, 2);
print(X);
# Take just the second column...
Y = X[, 1];
print(Y);
# ...and write it to a file.
write(Y, "Y.csv");
```
Afterwards, `Y.csv` should have the following contents:
```text
2
4
6
```
But it contains:
```text
2
3
4
```
This is a bug. Most likely, the `write`-kernel does not take the `rowSkip` of its input `DenseMatrix` into account when iterating over all values to write.

**Comment by AlexRTer** [comment]
I would like to be assigned to this issue please.

**Comment by pdamme** [comment]
Thanks, go ahead!
