### ISSUE TITLE
When casting as.matrix<f64>(), nrow and ncol does not work (defaults to 1)

### ISSUE THREAD

**Issue by bl1zzardx** [daphne-eu/daphne#682]
Hi,

I noticed when casting my matrix with as.matrix<f64>(), nrow and ncol does not work - defaults to 1. 
I am using the latest [daphne container](https://hub.docker.com/layers/daphneeu/daphne/2024-03-02_X86-64_BASE_ubuntu20.04/images/sha256-020f2e6132cc5e5fce01c0b1c11c91a6784967a4adc98c146c382ccc280d7ed7?context=explore) available on dockerhub. You might recreate the issue similarly as described in #681: 

> To recreate the problem, you would have to download x_valid.csv and y_valid.csv from [here](https://zenodo.org/records/10571936) and load it based on your setup. I include the respective csv.meta files here, you'd have to remove the .json ending to use them:
> 
> [y_valid.csv.meta](https://github.com/daphne-eu/daphne/files/14651775/y_valid.csv.meta.json)
> [x_valid.csv.meta](https://github.com/daphne-eu/daphne/files/14651776/x_valid.csv.meta.json)

```
def shape(df) {
    print("shape (" + nrow(df) + ", " + ncol(df) + ")");
    return nrow(df), ncol(df);
} 

def read_csv(path: str) -> matrix {
    df = readMatrix(path);  
    print("Read csv at " + path + ": ", 0); shape(df);
    # first row with column headers is turned to nan, thus ignored
    # first column has no header and only displays an unnecessary index, thus ignored
    return df[1:,1:]; 
}

# outputs correct nrow, ncol
# x_valid = rand(2000, 105, 1, 100, 0.5, 42); 

# outputs nrow=1, ncol=1, when cast with <f64>
x_valid = read_csv("/mnt/daphne_work/ifat_semiconductors/data/x_valid.csv"); 

shape(x_valid);

X = as.matrix<f64>(x_valid[0:1000, ]);
shape(X);

X = as.matrix(x_valid[0:1000, ]);
shape(X);
```

Output:
```
> daph /mnt/daphne_work/ifat_semiconductors/daphne/issue682.daph
Read csv at /mnt/daphne_work/ifat_semiconductors/data/x_valid.csv: shape (43615, 106)
shape (43614, 105)
shape (1, 1)
shape (1000, 105) 
```

**Comment by pdamme** [comment]
Thanks for reporting this issue. I can reproduce it (more precisely, I replaced the `readMatrix(path)` by `fill(123.456, 43615, 106)` to quickly test it without the files). And yes, this looks like a concrete example of #685.

**Comment by bl1zzardx** [comment]
fixed by now, no more shape (1, 1) with newer version of daphne
