### ISSUE TITLE
Data transfer with numpy for arrays of more than 2 dimensions

### ISSUE THREAD

**Issue by pdamme** [daphne-eu/daphne#711]
DaphneLib supports efficiently exchanging data with numpy via shared memory. However, at the moment, only numpy arrays with 1 or 2 dimensions are supported. Arrays with more than 2 dimensions should be supported as well. Inspiration can be taken from the data exchange with TensorFlow and PyTorch, where tensors with more than 2 dimensions are already supported.

**Comment by ldirry** [comment]
Hi, please assign me to this issue.

**Comment by philipportner** [comment]
@ldirry sure, go ahead.
