### ISSUE TITLE
Handle DAPHNE failure in DaphneLib

### ISSUE THREAD

**Issue by pdamme** [daphne-eu/daphne#717]
DaphneLib internally calls DAPHNE. More precisely, the Python function `execute()` in `src/api/python/daphne/script_building/script.py` calls the compiled C++ function `daphne()` in `src/api/daphnelib/daphnelib.cpp`, which in turn calls the compiled C++ function `mainInternal()` in `src/api/internal/daphne_internal.cpp`. `main_internal()` runs DAPHNE's entire parser/compiler/runtime stack. Currently, DaphneLib does not check if any error happened in DAPHNE nor does it react in any meaningful way. This should be improved for a more robust DaphneLib including meaningful error messages to DaphneLib users.

**Comment by saminbassiri** [comment]
Hi, Please assign me to this issue.

**Comment by philipportner** [comment]
Hey @saminbassiri , go ahead!
