### ISSUE TITLE
Clean up assertions in codebase

### ISSUE THREAD

**Issue by philipportner** [daphne-eu/daphne#720]
With #706 we moved a lot of `assert` to exceptions but there are still numerous `assert` left. `git grep "assert(" | wc -l` says `103`.
Goal is it to go through the codebase and replace `assert` with a `throw` statement where it makes sense.

**Comment by AlexRTer** [comment]
Hi, please assign me to this issue.

**Comment by pdamme** [comment]
Thanks @AlexRTer, good idea. Please go ahead!
