### ISSUE TITLE
`oneHot` and `bin` built-in functions in DaphneLib

### ISSUE THREAD

**Issue by pdamme** [daphne-eu/daphne#752]
A large fraction of the [DaphneDSL built-in functions](https://daphne-eu.github.io/daphne/DaphneDSL/Builtins/) is already supported in the [DaphneLib API](https://daphne-eu.github.io/daphne/DaphneLib/APIRef/). However, some typical functions for data preprocessing are still missing. This issue is about making the `oneHot` and `bin` built-in functions available on matrices in DaphneLib.

**Hints:**
- The code for DaphneLib can be found in `src/api/python/`. In particular, have a look at `src/api/python/operator/nodes/matrix.py`, where the already supported functions on matrices are implemented.
- Script-level test cases should be added in `test/api/python/`, where there are already several examples of equivalent DaphneLib/DaphneDSL scripts.
- It is fine to skip the `recode` built-in function for now, since it has two results -- a case that is not supported for DaphneLib built-in functions yet and that should thoroughly be addressed separately.

**Comment by saminbassiri** [comment]
Please assign me to this issue.

**Comment by pdamme** [comment]
Sure, go ahead!
