### ISSUE TITLE
Constant folding crashes for values of different types

### ISSUE THREAD

**Issue by pdamme** [daphne-eu/daphne#772]
[Constant folding](https://mlir.llvm.org/docs/Canonicalization/#canonicalizing-with-the-fold-method) enables the DAPHNE compiler to calculate many operations on constants already at compile-time. The respective code can be found in `src/ir/daphneir/DaphneDialect.cpp`.

For instance, in the following DaphneDSL script, constant folding evaluates 1 * 1 at compile-time, as can be seen when looking at the IR after parsing (no constant folding yet) and some initial simplifications (including constant folding) (use `--explain parsing,parsing_simplified`):

```R
print(1 * 1);
```

```
IR after parsing:
module {
  func.func @main() {
    %0 = "daphne.constant"() {value = 1 : si64} : () -> si64
    %1 = "daphne.constant"() {value = 1 : si64} : () -> si64
    %2 = "daphne.ewMul"(%0, %1) : (si64, si64) -> si64
    %3 = "daphne.constant"() {value = true} : () -> i1
    %4 = "daphne.constant"() {value = false} : () -> i1
    "daphne.print"(%2, %3, %4) : (si64, i1, i1) -> ()
    "daphne.return"() : () -> ()
  }
}
IR after parsing and some simplifications:
module {
  func.func @main() {
    %0 = "daphne.constant"() {value = 1 : si64} : () -> si64
    %1 = "daphne.constant"() {value = false} : () -> i1
    %2 = "daphne.constant"() {value = true} : () -> i1
    "daphne.print"(%0, %2, %1) : (si64, i1, i1) -> ()
    "daphne.return"() : () -> ()
  }
}
1
```

However, currently, constant folding requires the operands to have the same type. For instance, the following two DaphneDSL scripts would be perfectly amenable to constant folding, but make the DAPHNE compiler crash with the respective error messages:

- ```R
  print(1 * as.si32(1));
  ```
  ```
  daphne: /daphne/thirdparty/llvm-project/llvm/lib/Support/APInt.cpp:226: llvm::APInt llvm::APInt::operator*(const llvm::APInt &) const: Assertion `BitWidth == RHS.BitWidth && "Bit widths must be the same"' failed.
  ...
  Segmentation fault (core dumped)
  ```
- ```R
  print(1.0 * as.f32(1.0));
  ```
  ```
  daphne: /daphne/thirdparty/llvm-project/llvm/lib/Support/APFloat.cpp:1129: llvm::lostFraction llvm::detail::IEEEFloat::multiplySignificand(const llvm::detail::IEEEFloat &, llvm::detail::IEEEFloat): Assertion `semantics == rhs.semantics' failed.
  ...
  Segmentation fault (core dumped)
  ```

A possible solution could be to apply type promotion just like the DAPHNE compiler would do for runtime kernels.

**Comment by ldirry** [comment]
Hi, please assign me to this issue.

**Comment by philipportner** [comment]
> Hi, please assign me to this issue.

Sure, go ahead :)
