### ISSUE TITLE
Undetected invalid script args

### ISSUE THREAD

**Issue by pdamme** [daphne-eu/daphne#773]
When calling `daphne`, users can provide named *script arguments* that are available inside the DaphneDSL script. For a very simple example, see `test/api/cli/scriptargs/printSingleArg.daphne`:

```
print($foo);
```

According to the [DaphneDSL language reference](https://daphne-eu.github.io/daphne/DaphneDSL/LanguageRef/#script-arguments), only literals may be passed as script arguments. For example:

```bash
bin/daphne test/api/cli/scriptargs/printSingleArg.daphne foo=10
```
```
10
```

However, the following calls of `daphne` with invalid script arguments all pass "successfully" (status code 0) and some don't even indicate any error. Note that none of them behaves as one might expect when passing the respective invalid argument:

- ```bash
  # Unclear what the user may have wanted.
  bin/daphne test/api/cli/scriptargs/printSingleArg.daphne foo=10xyz23
  ```
  ```
  10
  ```
- ```bash
  # Seems like the user wanted DAPHNE to evaluate the expression.
  bin/daphne test/api/cli/scriptargs/printSingleArg.daphne foo="1.23*4.56"
  ```
  ```
  1.23
  ```
- ```bash
  # Seems like the user wanted DAPHNE to evaluate the expression.
  bin/daphne test/api/cli/scriptargs/printSingleArg.daphne foo="sin(1.23)"
  ```
  ```
  line 1:0 mismatched input 'sin' expecting {'true', 'false', INT_LITERAL, FLOAT_LITERAL, STRING_LITERAL}
  1.23
  ```

**Comment by pdamme** [comment]
Search for `see #773` in the code base.

**Comment by ldirry** [comment]
Hi, please assign me to this issue.
