### ISSUE TITLE
Simplification rewrites for elementwise unary minus (additive inverse)

### ISSUE THREAD

**Issue by pdamme** [daphne-eu/daphne#774]
DaphneDSL supports the elementwise additive inverse through the typical unary minus operator:
```
X = [1.1, 2.2, 3.3];
print(-X);
```

Internally, this operation is represented as a `EwMinusOp` in DaphneIR.

**Task:** This task is to add typical simplifications of this operation to the DAPHNE compiler, such as:
- *Constant folding:* Expressions like `-123` could be evaluated at compile-time.
- *Static rewrites:* E.g., `--x` to `x`.

Overall, such simplications can make the IR simpler and more readable, unlock further simplifications of consuming operations, and reduce the computational effort at run-time.

**Hints:**
- Get familiar with [canonicalization and constant folding in MLIR](https://mlir.llvm.org/docs/Canonicalization/).
- Have a look at the existing implementations of such simplifications for other DaphneIR operations in `src/ir/daphneir/DaphneDialect.cpp`.

**Comment by ldirry** [comment]
Hello, please assign me to this issue and #775 .

**Comment by pdamme** [comment]
Thanks for your interest. Sure, go ahead!
