### ISSUE TITLE
Support for unary minus in DaphneLib

### ISSUE THREAD

**Issue by pdamme** [daphne-eu/daphne#775]
The elementwise unary minus (additive inverse) operator has recently been added to DaphneDSL. This task is to add it to DaphneLib, DAPHNE's Python API as well.

**Hints:**
- The operator needs to be added to `src/api/python/daphne/operator/nodes/matrix.py` and `.../scalar.py`.

**Comment by ldirry** [comment]
Hello, please assign me to this issue and #774  .

**Comment by pdamme** [comment]
Thanks for your interest. Sure, go ahead!
