### ISSUE TITLE
Decision Tree test fails on some native builds

### ISSUE THREAD

**Issue by AlexRTer** [daphne-eu/daphne#787]
When running `test.sh [algorithms]`, the `randomForestWineReg_MaxV05` test (`test/api/cli/algorithms/DecisionTreeRandomForestTest.cpp`) fails consistently when checking accuracy on `Ubuntu 22.04 / 24.04` using `WSL2` (no docker container).
```
.../daphne/test/api/cli/algorithms/DecisionTreeRandomForestTest.cpp:49: FAILED:
  CHECK( acc >= minAcc )
with expansion:
  0.284802 >= 0.291
```
However, the issue does not occur when I built/ran daphne on `Ubuntu 20.04 / 22.04` using the docker container.

When running the equivalent command `./bin/daphne ./test/api/cli/algorithms/decisionTreeRealData3.daphne data=\"test/data/wine/winequality-red-white.csv\" dt=2 maxV=0.5` it outputs `0.292472` and `0.284802` consistently with and without the container respectively.

The setup used for the builds without containers can be reproduced using the script in #786.

**Comment by AlexRTer** [comment]
The error seems to stem from a call to `randomForest_.randomForest` in the script the test uses (`decisionTreeRealData3.daphne` l.80). Despite the seed being set `randSeeds` (l.106) is different (tested on 24.04 wsl vs 22.04 with docker). The error can be reproduced with the following script as well
```
X = rand(1, 1, 0, as.si64(1e6), 1, 1);
print(X);
```
which outputs 417022 (`24.04`) and 417115 (`22.04`).
Differences only occured when testing with values `>= 1e6` for the upper bound but were consistent between runs.

**Comment by corepointer** [comment]
The behavior of std::uniform_xxx_distribution seems to have changed. See this [discussion](https://stackoverflow.com/questions/74031210/c-deterministic-alternative-to-stduniform-xxx-distribution-with-mt19937) for more information. I'm relaxing the requirement on the failing test a bit which seems to solve the problem for now.
