### ISSUE TITLE
Help needed: Docker container daphneeu/daphne-dev:latest_X86-64_BASE exits with error

### ISSUE THREAD

**Issue by gmarkantonatos** [daphne-eu/daphne#817]
Hello, i am trying to run the Daphne docker container(daphneeu/daphne-dev:latest_X86-64_BASE) with windows, wsl and docker. I have followed your guide and got the container with docker pull daphneeu/daphne-dev:latest_X86-64_BASE. After that i use docker run daphneeu/daphne-dev and get the following error.
```
groupadd: invalid group ID ''
useradd: group '' does not exist
 ALL=(ALL:ALL) NOPASSWD:ALLWhat now? >>> /etc/sudoers: syntax error near line 31 <<<
chpasswd: (user ) pam_chauthtok() failed, error:
Authentication token manipulation error
chpasswd: (line 1, user ) password not changed

For longer running containers consider running 'unminimize' to update packages
and make the container more suitable for interactive use.

Use  with password Docker!3020 for SSH login
Docker Container IP address(es):
172.17.0.2
sudo: option requires an argument -- 'u'
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user]
            [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p
            prompt] [-T timeout] [-u user] file ...
```
Also i have tried to get inside the container with 
```
docker run -it --entrypoint /bin/bash <image name>
``` 
and run ```./entrypoint-interactive.sh ``` but get the same error

Can you help me fix the issue ?

**Comment by corepointer** [comment]
Try running the container with the script in ``containers/run-docker-example.sh``. If this works, you can build DAPHNE with ``./build.sh --no-deps --installPrefix /usr/local`` from the container shell. This avoids building all the dependencies and uses those installed in /usr/local in the container and saves you a lot of time.

**Comment by gmarkantonatos** [comment]
Thank you! I succeded in building thr project.
