### ISSUE TITLE
Duplication of libhdfs3 in build.sh

### ISSUE THREAD

**Issue by philipportner** [daphne-eu/daphne#827]
Commit 9c89049bef868f706738f2d0e6821d1b0ac7ef34 has introduced code to download and install `libhdfs3` . It seems to me that the code has been duplicated, although the two parts are not 100% the same.

- Part 1 is [here](https://github.com/daphne-eu/daphne/blob/d735331dc212be33b5872b1581285e97df263130/build.sh#L923-L949)
- Part 2 is [here](https://github.com/daphne-eu/daphne/blob/d735331dc212be33b5872b1581285e97df263130/build.sh#L969-L993)

I guess one of these have to be removed but I'm not sure which one :)

**Comment by corepointer** [comment]
Yes sorry I mixed some things up - fix is on the way

**Comment by philipportner** [comment]
> Yes sorry I mixed some things up - fix is on the way

Thanks for the quick fix @corepointer !
