### ISSUE TITLE
HDFS documentation

### ISSUE THREAD

**Issue by philipportner** [daphne-eu/daphne#838]
Recently, #767 has been merged into main. Currently, this is feature not documented. We should add documentation for this feature to make it easier for developers and users to use DAPHNE with HDFS support. This includes how to run DAPHNE with HDFS support, examples, required setup, limitations / drawbacks (and more).

**Comment by corepointer** [comment]
@corepointer likes labeling stuff :star_struck: 

Sorry for the noise :speak_no_evil:

**Comment by philipportner** [comment]
closed by 0091b98c4d31252d77cac8fdcb28de756ddce93f
