### ISSUE TITLE
MSTATIC documented scheduling option is missing

### ISSUE THREAD

**Issue by philipportner** [daphne-eu/daphne#892]
The modified version of static scheduling, `MSTATIC`, is [documented](https://github.com/daphne-eu/daphne/blob/e93c94345d3e6a79ff3bebde34c577c87a43278e/doc/SchedulingOptions.md?plain=1#L59), and exists as a CLI argument. 

However, this is not implemented in the [code](https://github.com/daphne-eu/daphne/blob/e93c94345d3e6a79ff3bebde34c577c87a43278e/src/runtime/local/vectorized/LoadPartitioning.h#L83-L152).

**Comment by jhmkorndorfer** [comment]
Good catch Philip. I just saw your issue and was curious about it, so I checked. I think there is no bug. It is probably a miss documentation/communication on our side. If you check the "default" scheduling strategy, it matches the description of MSTATIC. 

We need to fix that. I will get to it ASAP. In any case, now it basically means that if a user does not specify a scheduling technique, MSTATIC will be used which is not all bad as it usually outperforms "simple/naive" STATIC.

**Comment by philipportner** [comment]
> Good catch Philip. I just saw your issue and was curious about it, so I checked. I think there is no bug. It is probably a miss documentation/communication on our side. If you check the "default" scheduling strategy, it matches the description of MSTATIC.
> 
> We need to fix that. I will get to it ASAP. In any case, now it basically means that if a user does not specify a scheduling technique, MSTATIC will be used which is not all bad as it usually outperforms "simple/naive" STATIC.

Oh right, I didn't realize `default:` is actually `MSTATIC`, I guess simply adding a `case MSTATIC` should be fine. Thanks for pointing this out @jhmkorndorfer !
