### ISSUE TITLE
agg sum() of DaphneDSL does not work for aggregate per column

### ISSUE THREAD

**Issue by m-birke** [daphne-eu/daphne#909]
`sum(B, 1)` returns a scalar as `sum(B)` but should return a (1 x m) (row) matrix

```
B = fill(5,4,1);
print(sum(B, 1));
```

**Comment by philipportner** [comment]
Hi @m-birke , it's `fill(value:scalar, numRows:size, numCols:size)`, see [here](https://daphne-eu.github.io/daphne/DaphneDSL/Builtins/#data-generation).

This is sadly different (not sure why) to how numpy does it with [np.full](https://numpy.org/doc/stable/reference/generated/numpy.full.html), and should also require the shape to be passed as a shape/tuple so this mixup is not possible.

```
B = fill(1, 5, 4);
print(sum(B, 1));

DenseMatrix(1x4, int64_t)
5 5 5 5
```
